INSERT INTO client(id, name) VALUES ('COT', 'Continental');
INSERT INTO client(id, name) VALUES ('VAL', 'Valeo ');
INSERT INTO client(id, name) VALUES ('HEL', 'Hella');
INSERT INTO client(id, name) VALUES ('AUT', 'Autoliv');
INSERT INTO client(id, name) VALUES ('STC', 'strattec');
INSERT INTO client(id, name) VALUES ('BOS', 'Bosch');
INSERT INTO client(id, name) VALUES ('BRO', 'Brose ');
INSERT INTO client(id, name) VALUES ('DAN', 'Dana ');
INSERT INTO client(id, name) VALUES ('HDL', 'Honda Lock ');
INSERT INTO client(id, name) VALUES ('EES', 'Ethicon ');
INSERT INTO client(id, name) VALUES ('HIT', 'Hitachi ');
INSERT INTO client(id, name) VALUES ('MAG', 'Magna ');
INSERT INTO client(id, name) VALUES ('NID', 'Nidec ');
INSERT INTO client(id, name) VALUES ('SOG', 'Sogefi ');
INSERT INTO client(id, name) VALUES ('SEM', 'Sensata ');
INSERT INTO client(id, name) VALUES ('SEN', 'Sensata ');
INSERT INTO client(id, name) VALUES ('TRW', 'TRW');
INSERT INTO client(id, name) VALUES ('VER', 'Vermeer');
INSERT INTO client(id, name) VALUES ('DEN', 'Denso ');
INSERT INTO client(id, name) VALUES ('RIV', 'Rivian');
INSERT INTO client(id, name) VALUES ('MIT', 'Mitsumi ');
INSERT INTO client(id, name) VALUES ('ADV', 'Advanced ');
INSERT INTO client(id, name) VALUES ('ALH', 'Automotive Lighting');
INSERT INTO client(id, name) VALUES ('EFI', 'Electronics for imagin ');
INSERT INTO client(id, name) VALUES ('EMC', 'Emerson ');
INSERT INTO client(id, name) VALUES ('TEK', 'Teka ');
INSERT INTO client(id, name) VALUES ('XEN', 'Xenia');
INSERT INTO client(id, name) VALUES ('XXX', 'Defaut');
