--Revisar que tengan los clientes bien!!

INSERT INTO part(number, area, department, location, client) VALUES ('COT-7197-100-00', 'STA', 'Produccion ', 'Celda 1', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-5618-000-0C', 'STA', 'Produccion ', 'Celda 1', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-5619-000-0C', 'STA', 'Produccion ', 'Celda 1', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-7335-000-0A', 'STA', 'Produccion ', 'Celda 1', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-7336-000-0A', 'STA', 'Produccion ', 'Celda 1', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-7364-100', 'STA', 'Produccion ', 'Celda 1', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-7471-000-00', 'STA', 'Produccion ', 'Celda 1', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-7759-100', 'STA', 'Produccion ', 'Celda 1', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-7760-100', 'STA', 'Produccion ', 'Celda 1', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-7761 STAMP', 'STA', 'Produccion ', 'Celda 1', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-7782-101 ST', 'STA', 'Produccion ', 'Celda 1', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-7782-102 ST', 'STA', 'Produccion ', 'Celda 1', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-7787-201', 'STA', 'Produccion ', 'Celda 1', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-7787-202', 'STA', 'Produccion ', 'Celda 1', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-7787-211', 'STA', 'Produccion ', 'Celda 1', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-7793 STAMP', 'STA', 'Produccion ', 'Celda 1', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-8032-100', 'STA', 'Produccion ', 'Celda 1', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-8056-100', 'STA', 'Produccion ', 'Celda 1', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-8673-100', 'STA', 'Produccion ', 'Celda 1', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-8796-100-00', 'STA', 'Produccion ', 'Celda 1', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-8755-000', 'STA', 'Produccion ', 'Celda 1', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('ALH-6911-000-00', 'STA', 'Produccion ', 'Celda 1', 'ALH');
INSERT INTO part(number, area, department, location, client) VALUES ('ALH-6912-000-00', 'STA', 'Produccion ', 'Celda 1', 'ALH');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-6443-100-0A', 'STA', 'Produccion ', 'Celda 1', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-7749-100', 'STA', 'Produccion ', 'Celda 1', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-7327-000-00', 'STA', 'Produccion ', 'Celda 1', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('MIT-6336-000-00', 'STA', 'Produccion ', 'Celda 1', 'MIT');
INSERT INTO part(number, area, department, location, client) VALUES ('MIT-6337-100-00', 'STA', 'Produccion ', 'Celda 1', 'MIT');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-2881-101-0C', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-2882-100-0B', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-2883-100-0C', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-5957-200-0A', 'STA', 'Produccion ', 'Celda 1', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-5958-200-0A', 'STA', 'Produccion ', 'Celda 1', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-9917-200-00', 'STA', 'NPI', 'Celda 1', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-6033-100', 'STA', 'Produccion ', 'Celda 1', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-5952-000-00', 'STA', 'Produccion ', 'Celda 1', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-5953-000-00', 'STA', 'Produccion ', 'Celda 1', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-6428-300-00', 'STA', 'Produccion ', 'Celda 1', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('EMC-4067-200-00', 'STA', 'Produccion ', 'Celda 1', 'EMC');
INSERT INTO part(number, area, department, location, client) VALUES ('HDL-6100-100-00', 'STA', 'Produccion ', 'Celda 1', 'HDL');
INSERT INTO part(number, area, department, location, client) VALUES ('HDL-6514-000', 'STA', 'Produccion ', 'Celda 1', 'HDL');
INSERT INTO part(number, area, department, location, client) VALUES ('HDL-6515-000', 'STA', 'Produccion ', 'Celda 1', 'HDL');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-2340-100-00', 'STA', 'Produccion ', 'Celda 1', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('STC-6635-000-00', 'STA', 'Produccion ', 'Celda 1', 'STC');
INSERT INTO part(number, area, department, location, client) VALUES ('STC-7363-000-00', 'STA', 'Produccion ', 'Celda 1', 'STC');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-5874-101-0A', 'STA', 'Produccion ', 'Celda 1', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-5874-200-0A', 'STA', 'Produccion ', 'Celda 1', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-5957-200-0A', 'STA', 'Produccion ', 'Celda 1', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-5958-200-0A', 'STA', 'Produccion ', 'Celda 1', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-9917-200-00', 'STA', 'NPI', 'Celda 1', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-6033-100', 'STA', 'Produccion ', 'Celda 1', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-5952-000-00', 'STA', 'Produccion ', 'Celda 1', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-5953-000-00', 'STA', 'Produccion ', 'Celda 1', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-6428-300-00', 'STA', 'Produccion ', 'Celda 1', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('EMC-4067-200-00', 'STA', 'Produccion ', 'Celda 1', 'EMC');
INSERT INTO part(number, area, department, location, client) VALUES ('HDL-6100-100-00', 'STA', 'Produccion ', 'Celda 1', 'HDL');
INSERT INTO part(number, area, department, location, client) VALUES ('HDL-6514-000', 'STA', 'Produccion ', 'Celda 1', 'HDL');
INSERT INTO part(number, area, department, location, client) VALUES ('HDL-6515-000', 'STA', 'Produccion ', 'Celda 1', 'HDL');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-2340-100-00', 'STA', 'Produccion ', 'Celda 1', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('STC-6635-000-00', 'STA', 'Produccion ', 'Celda 1', 'STC');
INSERT INTO part(number, area, department, location, client) VALUES ('STC-7363-000-00', 'STA', 'Produccion ', 'Celda 1', 'STC');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-5874-101-0A', 'STA', 'Produccion ', 'Celda 1', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-5874-200-0A', 'STA', 'Produccion ', 'Celda 1', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-4106-200-00', 'STA', 'Produccion ', 'Celda 1', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-6194-102-00', 'STA', 'Produccion ', 'Celda 1', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-3051-000-0L', 'STA', 'Produccion ', 'Celda 1', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-5552-100-0A', 'STA', 'Produccion ', 'Celda 1', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-5552-300', 'STA', 'Produccion ', 'Celda 1', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-5999-300-00', 'STA', 'Produccion ', 'Celda 1', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-5362-000-0B', 'STA', 'Produccion ', 'Celda 1', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-5363-000-0B', 'STA', 'Produccion ', 'Celda 1', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('EES-5721-100', 'STA', 'Produccion ', 'Celda 1', 'EES');
INSERT INTO part(number, area, department, location, client) VALUES ('EPQ-5496-200-0A', 'STA', 'Produccion ', 'Celda 1', 'EPQ');
INSERT INTO part(number, area, department, location, client) VALUES ('HDL-6257-100-00', 'STA', 'Produccion ', 'Celda 1', 'HDL');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-0484-100-00', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('SEN-8275-200-00', 'STA', 'Produccion ', 'Celda 1', 'SEN');
INSERT INTO part(number, area, department, location, client) VALUES ('SEN-8278-200-00', 'STA', 'Produccion ', 'Celda 1', 'SEN');
INSERT INTO part(number, area, department, location, client) VALUES ('SEN-8546-200', 'STA', 'Produccion ', 'Celda 1', 'SEN');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-5873-100-0B', 'STA', 'Produccion ', 'Celda 1', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-3051-000-0L', 'STA', 'Produccion ', 'Celda 1', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('DAN-10000-100', 'STA', 'Produccion ', 'Celda 1', 'DAN');
INSERT INTO part(number, area, department, location, client) VALUES ('DAN-9999-200', 'STA', 'Produccion ', 'Celda 1', 'DAN');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-0481-200-00', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-0482-200-00', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-0484-100-00', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-0485-100-00', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-0723-100-00', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-0994-000-0G', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-2853-100-00', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('SEN-8275-200-00', 'STA', 'Produccion ', 'Celda 1', 'SEN');
INSERT INTO part(number, area, department, location, client) VALUES ('SEN-8278-200-00', 'STA', 'Produccion ', 'Celda 1', 'SEN');
INSERT INTO part(number, area, department, location, client) VALUES ('SEN-8546-200', 'STA', 'Produccion ', 'Celda 1', 'SEN');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-7567-300', 'STA', 'NPI', 'Celda 1', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-7107-100-00', 'STA', 'Produccion ', 'Celda 1', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-7460-202-00', 'STA', 'Produccion ', 'Celda 1', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('HDL-6107-100-00', 'STA', 'Produccion ', 'Celda 1', 'HDL');
INSERT INTO part(number, area, department, location, client) VALUES ('HIT-7010-200-0A', 'STA', 'Produccion ', 'Celda 1', 'HIT');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-5873-101-00', 'STA', 'Produccion ', 'Celda 1', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-5875-100', 'STA', 'Produccion ', 'Celda 1', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-5876-100-0A', 'STA', 'Produccion ', 'Celda 1', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-7405-000', 'STA', 'Produccion ', 'Celda 1', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-6194-300-00', 'STA', 'Produccion ', 'Celda 1', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-6194-301-00', 'STA', 'Produccion ', 'Celda 1', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-6313-000-00', 'STA', 'Produccion ', 'Celda 1', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-6314-000-00', 'STA', 'Produccion ', 'Celda 1', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-6734-101-00', 'STA', 'Produccion ', 'Celda 1', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-7370-200-00', 'STA', 'Produccion ', 'Celda 1', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-7567-300', 'STA', 'NPI', 'Celda 1', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-5671-200-0B', 'STA', 'Produccion ', 'Celda 1', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-5746-200-00', 'STA', 'Produccion ', 'Celda 1', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-7107-100-00', 'STA', 'Produccion ', 'Celda 1', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-7460-202-00', 'STA', 'Produccion ', 'Celda 1', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('EFI-7326-200', 'STA', 'Produccion ', 'Celda 1', 'EFI');
INSERT INTO part(number, area, department, location, client) VALUES ('EFI-7683-200-00', 'STA', 'Produccion ', 'Celda 1', 'EFI');
INSERT INTO part(number, area, department, location, client) VALUES ('EFI-7711-200-00', 'STA', 'Produccion ', 'Celda 1', 'EFI');
INSERT INTO part(number, area, department, location, client) VALUES ('EFI-7854-200-0A', 'STA', 'Produccion ', 'Celda 1', 'EFI');
INSERT INTO part(number, area, department, location, client) VALUES ('EFI-7855-200', 'STA', 'Produccion ', 'Celda 1', 'EFI');
INSERT INTO part(number, area, department, location, client) VALUES ('HDL-6107-100-00', 'STA', 'Produccion ', 'Celda 1', 'HDL');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-5873-101-00', 'STA', 'Produccion ', 'Celda 1', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-5875-100', 'STA', 'Produccion ', 'Celda 1', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-5876-100-0A', 'STA', 'Produccion ', 'Celda 1', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-7405-000', 'STA', 'Produccion ', 'Celda 1', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('VAL-5061-103-0F', 'STA', 'Produccion ', 'Celda 1', 'VAL');
INSERT INTO part(number, area, department, location, client) VALUES ('VAL-8422-101', 'STA', 'Produccion ', 'Celda 1', 'VAL');
INSERT INTO part(number, area, department, location, client) VALUES ('VAL-8422-102', 'STA', 'Produccion ', 'Celda 1', 'VAL');
INSERT INTO part(number, area, department, location, client) VALUES ('VAL-8422-103', 'STA', 'Produccion ', 'Celda 1', 'VAL');
INSERT INTO part(number, area, department, location, client) VALUES ('VAL-8422-104', 'STA', 'Produccion ', 'Celda 1', 'VAL');
INSERT INTO part(number, area, department, location, client) VALUES ('VAL-8422-105', 'STA', 'Produccion ', 'Celda 1', 'VAL');
INSERT INTO part(number, area, department, location, client) VALUES ('VAL-8422-106', 'STA', 'Produccion ', 'Celda 1', 'VAL');
INSERT INTO part(number, area, department, location, client) VALUES ('VAL-8422-302', 'STA', 'Produccion ', 'Celda 1', 'VAL');
INSERT INTO part(number, area, department, location, client) VALUES ('VAL-8422-303', 'STA', 'Produccion ', 'Celda 1', 'VAL');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-6194-300-00', 'STA', 'Produccion ', 'Celda 1', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-6194-301-00', 'STA', 'Produccion ', 'Celda 1', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-6313-000-00', 'STA', 'Produccion ', 'Celda 1', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-6314-000-00', 'STA', 'Produccion ', 'Celda 1', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-6734-101-00', 'STA', 'Produccion ', 'Celda 1', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-7370-200-00', 'STA', 'Produccion ', 'Celda 1', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-7567-300', 'STA', 'NPI', 'Celda 1', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-5671-200-0B', 'STA', 'Produccion ', 'Celda 1', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-5746-200-00', 'STA', 'Produccion ', 'Celda 1', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-7107-100-00', 'STA', 'Produccion ', 'Celda 1', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-7460-202-00', 'STA', 'Produccion ', 'Celda 1', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('EFI-7326-200', 'STA', 'Produccion ', 'Celda 1', 'EFI');
INSERT INTO part(number, area, department, location, client) VALUES ('EFI-7683-200-00', 'STA', 'Produccion ', 'Celda 1', 'EFI');
INSERT INTO part(number, area, department, location, client) VALUES ('EFI-7711-200-00', 'STA', 'Produccion ', 'Celda 1', 'EFI');
INSERT INTO part(number, area, department, location, client) VALUES ('EFI-7854-200-0A', 'STA', 'Produccion ', 'Celda 1', 'EFI');
INSERT INTO part(number, area, department, location, client) VALUES ('EFI-7855-200', 'STA', 'Produccion ', 'Celda 1', 'EFI');
INSERT INTO part(number, area, department, location, client) VALUES ('HDL-6107-100-00', 'STA', 'Produccion ', 'Celda 1', 'HDL');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-5873-101-00', 'STA', 'Produccion ', 'Celda 1', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-5875-100', 'STA', 'Produccion ', 'Celda 1', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-5876-100-0A', 'STA', 'Produccion ', 'Celda 1', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-7405-000', 'STA', 'Produccion ', 'Celda 1', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('VAL-5061-103-0F', 'STA', 'Produccion ', 'Celda 1', 'VAL');
INSERT INTO part(number, area, department, location, client) VALUES ('VAL-8422-101', 'STA', 'Produccion ', 'Celda 1', 'VAL');
INSERT INTO part(number, area, department, location, client) VALUES ('VAL-8422-102', 'STA', 'Produccion ', 'Celda 1', 'VAL');
INSERT INTO part(number, area, department, location, client) VALUES ('VAL-8422-103', 'STA', 'Produccion ', 'Celda 1', 'VAL');
INSERT INTO part(number, area, department, location, client) VALUES ('VAL-8422-104', 'STA', 'Produccion ', 'Celda 1', 'VAL');
INSERT INTO part(number, area, department, location, client) VALUES ('VAL-8422-105', 'STA', 'Produccion ', 'Celda 1', 'VAL');
INSERT INTO part(number, area, department, location, client) VALUES ('VAL-8422-106', 'STA', 'Produccion ', 'Celda 1', 'VAL');
INSERT INTO part(number, area, department, location, client) VALUES ('VAL-8422-302', 'STA', 'Produccion ', 'Celda 1', 'VAL');
INSERT INTO part(number, area, department, location, client) VALUES ('VAL-8422-303', 'STA', 'Produccion ', 'Celda 1', 'VAL');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-5957-000-0A', 'STA', 'Produccion ', 'Celda 1', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-5958-000-0A', 'STA', 'Produccion ', 'Celda 1', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('EMC-3794-100-00', 'STA', 'Produccion ', 'Celda 1', 'EMC');
INSERT INTO part(number, area, department, location, client) VALUES ('HDL-6257-100-00', 'STA', 'Produccion ', 'Celda 1', 'HDL');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-0741-100-00', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-0742-100-00', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-0799-100-00', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-0810-100-00', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-0820-300-00', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-2920-100-0D', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-2920-101-0D', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-2923-100-00', 'STA', 'Produccion ', 'Celda 1', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-2924-100-00', 'STA', 'Produccion ', 'Celda 1', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-2925-100-00', 'STA', 'Produccion ', 'Celda 1', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('VAL-6652-301', 'STA', 'Produccion ', 'Celda 1', 'VAL');
INSERT INTO part(number, area, department, location, client) VALUES ('VAL-7121-301', 'STA', 'Produccion ', 'Celda 1', 'VAL');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-2964-000-0D', 'STA', 'Produccion ', 'Celda 1', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-6550-100-00', 'STA', 'Produccion ', 'Celda 1', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-7105-100-00', 'STA', 'Produccion ', 'Celda 1', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-8381-100', 'STA', 'Produccion ', 'Celda 1', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-8381-300', 'STA', 'Produccion ', 'Celda 1', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-3658-000-0C', 'STA', 'Produccion ', 'Celda 1', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-3659-000-0C', 'STA', 'Produccion ', 'Celda 1', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-3686-000-0E', 'STA', 'Produccion ', 'Celda 1', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-3687-000-0E', 'STA', 'Produccion ', 'Celda 1', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-3688-000-0C', 'STA', 'Produccion ', 'Celda 1', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-3689-000-0C', 'STA', 'Produccion ', 'Celda 1', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-5859-100-00', 'STA', 'Produccion ', 'Celda 1', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-6428-103-00', 'STA', 'Produccion ', 'Celda 1', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-6428-104-00', 'STA', 'Produccion ', 'Celda 1', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-6428-105-00', 'STA', 'Produccion ', 'Celda 1', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-6428-106-00', 'STA', 'Produccion ', 'Celda 1', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('EES-3647-100-00', 'STA', 'Produccion ', 'Celda 1', 'EES');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-1630-100-00', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-2277-000-0W', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-2920-100-0D', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-2920-101-0D', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-5877-100', 'STA', 'Produccion ', 'Celda 1', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-4405-000-0I', 'STA', 'Produccion ', 'Celda 1', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-4406-000-0I', 'STA', 'Produccion ', 'Celda 1', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-5134-100-00', 'STA', 'Produccion ', 'Celda 1', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('FTE-1356-200-00', 'STA', 'Produccion ', 'Celda 1', 'FTE');
INSERT INTO part(number, area, department, location, client) VALUES ('HDL-6210-100-00', 'STA', 'Produccion ', 'Celda 1', 'HDL');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-2196-100-00', 'STA', 'Produccion ', 'Celda 1', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-2197-100-00', 'STA', 'Produccion ', 'Celda 1', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-2855-100-00', 'STA', 'Produccion ', 'Celda 1', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-6151-100-00', 'STA', 'Produccion ', 'Celda 1', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('MIT-6338-000-00', 'STA', 'Produccion ', 'Celda 1', 'MIT');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-1252-200-00', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-2572-200-00', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-3874-100-00', 'STA', 'Produccion ', 'Celda 1', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('VAL-6652-302', 'STA', 'Produccion ', 'Celda 1', 'VAL');
INSERT INTO part(number, area, department, location, client) VALUES ('VAL-7121-302', 'STA', 'Produccion ', 'Celda 1', 'VAL');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-9304-000', 'STA', 'NPI', 'Celda 1', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-9307-000', 'STA', 'NPI', 'Celda 1', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-8585-100', 'STA', 'NPI', 'Celda 1', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-8585-101', 'STA', 'NPI', 'Celda 1', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-8585-102', 'STA', 'NPI', 'Celda 1', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-4528-000-0L', 'STA', 'Produccion ', 'Celda 1', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-5507-000-0C', 'STA', 'Produccion ', 'Celda 1', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-5508-000-0C', 'STA', 'Produccion ', 'Celda 1', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-5618-000-0C', 'STA', 'Produccion ', 'Celda 1', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-5619-000-0C', 'STA', 'Produccion ', 'Celda 1', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-5636-000-0D', 'STA', 'Produccion ', 'Celda 1', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-7335-000-0A', 'STA', 'Produccion ', 'Celda 1', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-7336-000-0A', 'STA', 'Produccion ', 'Celda 1', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('EMC-3790-000-0H', 'STA', 'Produccion ', 'Celda 1', 'EMC');
INSERT INTO part(number, area, department, location, client) VALUES ('EMC-4918-200-0A', 'STA', 'Produccion ', 'Celda 1', 'EMC');
INSERT INTO part(number, area, department, location, client) VALUES ('EMC-7272-200-00', 'STA', 'Produccion ', 'Celda 1', 'EMC');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-7787-201', 'STA', 'Produccion ', 'Celda 1', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-7787-202', 'STA', 'Produccion ', 'Celda 1', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-7787-211', 'STA', 'Produccion ', 'Celda 1', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('IMT-2831-000-0B', 'STA', 'Produccion ', 'Celda 1', 'IMT');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-1447-300-ST', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('VAL-5060-100-0F', 'STA', 'Produccion ', 'Celda 1', 'VAL');
INSERT INTO part(number, area, department, location, client) VALUES ('VAL-5061-102-0G', 'STA', 'Produccion ', 'Celda 1', 'VAL');
INSERT INTO part(number, area, department, location, client) VALUES ('VAL-6385-000-0A', 'STA', 'Produccion ', 'Celda 1', 'VAL');
INSERT INTO part(number, area, department, location, client) VALUES ('VAL-6652-300', 'STA', 'Produccion ', 'Celda 1', 'VAL');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-7105-000-00', 'STA', 'Produccion ', 'Celda 1', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-7107-000-00', 'STA', 'Produccion ', 'Celda 1', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-9670-000', 'STA', 'NPI', 'Celda 1', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-9304-100', 'STA', 'NPI', 'Celda 1', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-9307-100', 'STA', 'NPI', 'Celda 1', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-9670-100', 'STA', 'NPI', 'Celda 1', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('BRO-9112-300-00', 'STA', 'NPI', 'Celda 1', 'BRO');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-6033-000', 'STA', 'Produccion ', 'Celda 1', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-6033-200', 'STA', 'Produccion ', 'Celda 1', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-6443-000-0A', 'STA', 'Produccion ', 'Celda 1', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-7197-000-00', 'STA', 'Produccion ', 'Celda 1', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-5134-000-0C', 'STA', 'Produccion ', 'Celda 1', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('HDL-6100-000-00', 'STA', 'Produccion ', 'Celda 1', 'HDL');
INSERT INTO part(number, area, department, location, client) VALUES ('HDL-6100-200', 'STA', 'Produccion ', 'Celda 1', 'HDL');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-5859-000-00', 'STA', 'Produccion ', 'Celda 1', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('HDL-6107-000-00', 'STA', 'Produccion ', 'Celda 1', 'HDL');
INSERT INTO part(number, area, department, location, client) VALUES ('HDL-6107-100', 'STA', 'Produccion ', 'Celda 1', 'HDL');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-7782-001 FERT', 'STA', 'Produccion ', 'Celda 1', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('HDL-6100-100', 'STA', 'Produccion ', 'Celda 1', 'HDL');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-7782-001 SLO', 'STA', 'Produccion ', 'Celda 1', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-7782-002 FERT', 'STA', 'Produccion ', 'Celda 1', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-7782-002 SLO', 'STA', 'Produccion ', 'Celda 1', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('NID-10009-100', 'STA', 'Produccion ', 'Celda 1', 'NID');
INSERT INTO part(number, area, department, location, client) VALUES ('NID-10009-000', 'STA', 'Produccion ', 'Celda 1', 'NID');
INSERT INTO part(number, area, department, location, client) VALUES ('NID-10006-000', 'STA', 'Produccion ', 'Celda 1', 'NID');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-0741-000-0M', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-0741-200-00', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-0799-000-0L', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-0799-200-00', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-0482-000-0D', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-0482-000-0D', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-2572-000-0D', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-0484-000-0A', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-1630-000-0B', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('SEN-8442-200-00', 'STA', 'Produccion ', 'Celda 1', 'SEN');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-3874-000-0C', 'STA', 'Produccion ', 'Celda 1', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-8032 STAMP', 'STA', 'Produccion ', 'Celda 1', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-8755-100', 'STA', 'Produccion ', 'Celda 1', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-8673-000', 'STA', 'Produccion ', 'Celda 1', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-8381-000', 'STA', 'Produccion ', 'Celda 1', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-5746-000-0A', 'STA', 'Produccion ', 'Celda 1', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-9997-100', 'STA', 'Produccion ', 'Celda 1', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('HDL-6210-000-00', 'STA', 'Produccion ', 'Celda 1', 'HDL');
INSERT INTO part(number, area, department, location, client) VALUES ('RIV-9744-000-0B', 'STA', 'NPI', 'Celda 4', 'RIV');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-0741-000-0M', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-0741-200-00', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-0799-000-0L', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-1630-000-0B', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-0820-000-0F', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('SEN-8442-200-00', 'STA', 'Produccion ', 'Celda 1', 'SEN');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-1630-000-0B', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('SEN-8442-200-00', 'STA', 'Produccion ', 'Celda 1', 'SEN');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-3874-000-0C', 'STA', 'Produccion ', 'Celda 1', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-8032 STAMP', 'STA', 'Produccion ', 'Celda 1', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-8755-100', 'STA', 'Produccion ', 'Celda 1', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-8673-000', 'STA', 'Produccion ', 'Celda 1', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-5746-100-00', 'STA', 'Produccion ', 'Celda 1', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-7749-000-00', 'STA', 'Produccion ', 'Celda 1', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('DAN-9999-300', 'STA', 'Produccion ', 'Celda 1', 'DAN');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-7749-100-00', 'STA', 'Produccion ', 'Celda 1', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-2340-000-0K', 'STA', 'Produccion ', 'Celda 1', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-0481-000-0A', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-8796-000', 'STA', 'Produccion ', 'Celda 1', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('RIV-9744-000', 'STA', 'NPI', 'Celda 4', 'RIV');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-0742-200-00', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-0742-000-0R', 'STA', 'Produccion ', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-2853-000-0F', 'STA', '', 'Celda 1', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('RIV-9744-200', 'STA', 'NPI', 'Celda 1', 'RIV');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-7567-000', 'Molding', 'NPI', 'Celda 4', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-9224-100-00', 'Molding', 'NPI', 'Celda 4', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('BRO-9112-000-00', 'Molding', 'NPI', 'Celda 3', 'BRO');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-6798-000-00', 'Molding', 'Produccion ', 'Celda 7', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-6798-080-00', 'Molding', 'Produccion ', 'Celda 7', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('VAL-8422-000-00', 'Molding', 'Produccion ', 'Celda 7', 'VAL');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-7370-000-00', 'Molding', 'Produccion ', 'Celda 5', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-7567-000', 'Molding', 'NPI', 'Celda 4', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-6151-000-AB', 'Molding', 'Produccion ', 'Celda 5', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-2920-000-0R', 'Molding', 'Produccion ', 'Celda 7', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-5876-000-0B', 'Molding', 'Produccion ', 'Celda 6', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-5877-000-0C', 'Molding', 'Produccion ', 'Celda 6', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-6725-000-00', 'Molding', 'Produccion ', 'Celda 7', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-6798-GR10', 'Molding', 'Produccion ', 'Celda 7', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-7459-100-00', 'Molding', 'Produccion ', 'Celda 6', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-7460-100-00', 'Molding', 'Produccion ', 'Celda 6', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-6194-000', 'Molding', 'Produccion ', 'Celda 7', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-6428-000-00', 'Molding', 'Produccion ', 'Celda 7', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('SOG-8423-000', 'Molding', 'Produccion ', 'Celda 7', 'SOG');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-7614-000', 'Molding', 'Produccion ', 'Celda 7', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('SEN-8275-000-00', 'Molding', 'Produccion ', 'Celda 4', 'SEN');
INSERT INTO part(number, area, department, location, client) VALUES ('VAL-6652-000-00', 'Molding', 'Produccion ', 'Celda 3', 'VAL');
INSERT INTO part(number, area, department, location, client) VALUES ('VAL-7121-000-00', 'Molding', 'Produccion ', 'Celda 3', 'VAL');
INSERT INTO part(number, area, department, location, client) VALUES ('VAL-8187-000-00', 'Molding', 'Produccion ', 'Celda 3', 'VAL');
INSERT INTO part(number, area, department, location, client) VALUES ('VAL-8834-000-00', 'Molding', 'Produccion ', 'Celda 3', 'VAL');
INSERT INTO part(number, area, department, location, client) VALUES ('SEN-8278-000', 'Molding', 'Produccion ', 'Celda 4', 'SEN');
INSERT INTO part(number, area, department, location, client) VALUES ('SEN-8515-000', 'Molding', 'NPI', 'Celda 6', 'SEN');
INSERT INTO part(number, area, department, location, client) VALUES ('SEN-8524-000', 'Molding', 'Produccion ', 'Celda 4', 'SEN');
INSERT INTO part(number, area, department, location, client) VALUES ('SEN-8546-000', 'Molding', 'Produccion ', 'Celda 4', 'SEN');
INSERT INTO part(number, area, department, location, client) VALUES ('SEN-8547-000', 'Molding', 'Produccion ', 'Celda 4', 'SEN');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-4106-000-00', 'Molding', 'Produccion ', 'Celda 5', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-3266-000-0H', 'Molding', 'Produccion ', 'Celda 6', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-9265-000', 'Molding', 'Produccion ', 'Celda 6', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('VAL-5061-100-0E', 'Molding', 'Produccion ', 'Celda 6', 'VAL');
INSERT INTO part(number, area, department, location, client) VALUES ('VAL-5061-101-0D', 'Molding', 'Produccion ', 'Celda 6', 'VAL');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-8585-103', 'Molding', 'NPI', 'Celda 4', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-8585-104', 'Molding', 'NPI', 'Celda 4', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-8251-102', 'Molding', 'Produccion ', 'Celda 4', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-9997-000', 'Molding', 'Produccion ', 'Celda 6', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('DAN-10000-000', 'Molding', 'Produccion ', 'Celda 7', 'DAN');
INSERT INTO part(number, area, department, location, client) VALUES ('DAN-9999-000', 'Molding', 'Produccion ', 'Celda 7', 'DAN');
INSERT INTO part(number, area, department, location, client) VALUES ('HIT-10001-000', 'Molding', 'Produccion ', 'Celda 7', 'HIT');
INSERT INTO part(number, area, department, location, client) VALUES ('ITV-10005-000', 'STA', 'Produccion ', 'Celda 1', 'ITV');
INSERT INTO part(number, area, department, location, client) VALUES ('NID-10007-000', 'Molding', 'Produccion ', 'Celda 7', 'NID');
INSERT INTO part(number, area, department, location, client) VALUES ('VER-10011-000-ACC', 'Molding', 'Produccion ', 'Celda 7', 'VER');
INSERT INTO part(number, area, department, location, client) VALUES ('VER-10011-000-NOR', 'Molding', 'Produccion ', 'Celda 7', 'VER');
INSERT INTO part(number, area, department, location, client) VALUES ('VER-10012-200', 'Molding', 'Produccion ', 'Celda 7', 'VER');
INSERT INTO part(number, area, department, location, client) VALUES ('VER-10012-300', 'Molding', 'Produccion ', 'Celda 7', 'VER');
INSERT INTO part(number, area, department, location, client) VALUES ('VER-10012-400', 'Molding', 'Produccion ', 'Celda 7', 'VER');
INSERT INTO part(number, area, department, location, client) VALUES ('VER-10013-000', 'Molding', 'Produccion ', 'Celda 7', 'VER');
INSERT INTO part(number, area, department, location, client) VALUES ('VER-10013-100', 'Molding', 'Produccion ', 'Celda 7', 'VER');
INSERT INTO part(number, area, department, location, client) VALUES ('VER-10013-200', 'Molding', 'Produccion ', 'Celda 7', 'VER');
INSERT INTO part(number, area, department, location, client) VALUES ('VER-10014-000', 'Molding', 'Produccion ', 'Celda 7', 'VER');
INSERT INTO part(number, area, department, location, client) VALUES ('VER-10014-100', 'Molding', 'Produccion ', 'Celda 7', 'VER');
INSERT INTO part(number, area, department, location, client) VALUES ('VER-10014-200', 'Molding', 'Produccion ', 'Celda 7', 'VER');
INSERT INTO part(number, area, department, location, client) VALUES ('VER-10014-300', 'Molding', 'Produccion ', 'Celda 7', 'VER');
INSERT INTO part(number, area, department, location, client) VALUES ('XEN-9985-000', 'Molding', 'Produccion ', 'Celda 7', 'XEN');
INSERT INTO part(number, area, department, location, client) VALUES ('BRO-10027-000-CN', 'Molding', 'Produccion ', 'Celda 5', 'BRO');
INSERT INTO part(number, area, department, location, client) VALUES ('BRO-10027-000-MX', 'Molding', 'Produccion ', 'Celda 5', 'BRO');
INSERT INTO part(number, area, department, location, client) VALUES ('BRO-10024-000', 'Molding', 'Produccion ', 'Celda 6', 'BRO');
INSERT INTO part(number, area, department, location, client) VALUES ('EES-4749-000-00', 'Molding', 'Produccion ', 'Celda 6', 'EES');
INSERT INTO part(number, area, department, location, client) VALUES ('EES-4749-200-00', 'Molding', 'Produccion ', 'Celda 3', 'EES');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-6734-100-00', 'Molding', 'Produccion ', 'Celda 6', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('VAL-5235-000-0E', 'Molding', 'Produccion ', 'Celda 6', 'VAL');
INSERT INTO part(number, area, department, location, client) VALUES ('EES-5107-000-0A', 'Molding', 'Produccion ', 'Celda 3', 'EES');
INSERT INTO part(number, area, department, location, client) VALUES ('VAL-5060-101-0G', 'Molding', 'Produccion ', 'Celda 6', 'VAL');
INSERT INTO part(number, area, department, location, client) VALUES ('VAL-5061-104-0F', 'Molding', 'Produccion ', 'Celda 6', 'VAL');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-3404-000-0O', 'Molding', 'Produccion ', 'Celda 5', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-5873-000-0D', 'Molding', 'Produccion ', 'Celda 5', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-5874-000-0B', 'Molding', 'Produccion ', 'Celda 5', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-9917-000', 'Molding', 'NPI', 'Celda 4', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-9918-000', 'Molding', 'NPI', 'Celda 4', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-10002-000', 'Molding', 'Produccion ', 'Celda 6', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-7787-000', 'Molding', 'Produccion ', 'Celda 6', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-7787-010', 'Molding', 'Produccion ', 'Celda 6', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-6734-000-00', 'Molding', 'Produccion ', 'Celda 4', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-6734-SLP-00', 'Molding', 'Produccion ', 'Celda 4', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-9224-000', 'Molding', 'NPI', 'Celda 4', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-8585-000', 'Molding', 'NPI', 'Celda 5', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-7459-000-00', 'Molding', 'Produccion ', 'Celda 5', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-7460-000-00', 'Molding', 'Produccion ', 'Celda 5', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-8251-000', 'Molding', 'Produccion ', 'Celda 4', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('MIT-6337-000-00', 'Molding', 'Produccion ', 'Celda 3', 'MIT');
INSERT INTO part(number, area, department, location, client) VALUES ('080-000020', 'Molding', 'Produccion ', 'Celda 3', 'XXX');
INSERT INTO part(number, area, department, location, client) VALUES ('6412-01 SUB ASSY', 'Molding', 'Produccion ', 'Celda 3', 'XXX');
INSERT INTO part(number, area, department, location, client) VALUES ('6412-02 SUB ASSY', 'Molding', 'Produccion ', 'Celda 3', 'XXX');
INSERT INTO part(number, area, department, location, client) VALUES ('6412-03 SUB ASSY', 'Molding', 'Produccion ', 'Celda 3', 'XXX');
INSERT INTO part(number, area, department, location, client) VALUES ('6412-A05 SUB ASSY', 'Molding', 'Produccion ', 'Celda 3', 'XXX');
INSERT INTO part(number, area, department, location, client) VALUES ('MAG-8792-000', 'Molding', 'Produccion ', 'Celda 3', 'MAG');
INSERT INTO part(number, area, department, location, client) VALUES ('MAG-8793-000', 'Molding', 'Produccion ', 'Celda 3', 'MAG');
INSERT INTO part(number, area, department, location, client) VALUES ('MAG-8794-000', 'Molding', 'Produccion ', 'Celda 3', 'MAG');
INSERT INTO part(number, area, department, location, client) VALUES ('TEK-8788-000', 'Molding', 'Produccion ', 'Celda 3', 'TEK');
INSERT INTO part(number, area, department, location, client) VALUES ('TEK-8791-000', 'Molding', 'Produccion ', 'Celda 3', 'TEK');
INSERT INTO part(number, area, department, location, client) VALUES ('VAL-5060-000-0O', 'Molding', 'Produccion ', 'Celda 6', 'VAL');
INSERT INTO part(number, area, department, location, client) VALUES ('VAL-5061-000-0N', 'Molding', 'Produccion ', 'Celda 6', 'VAL');
INSERT INTO part(number, area, department, location, client) VALUES ('VER-10012-000', 'Molding', 'Produccion ', 'Celda 7', 'VER');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-6550-000-0A', 'Molding', 'Produccion ', 'Celda 6', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('EES-4749-100-00', 'Molding', 'Produccion ', 'Celda 6', 'EES');
INSERT INTO part(number, area, department, location, client) VALUES ('HDL-6257-000-0A', 'Molding', 'Produccion ', 'Celda 7', 'HDL');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-6151-000-AB', 'Molding', 'Produccion ', 'Celda 5', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-5552-000-0G', 'Molding', 'Produccion ', 'Celda 7', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-2881-000-0L', 'Molding', 'Produccion ', 'Celda 7', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-2882-000-0W', 'Molding', 'Produccion ', 'Celda 7', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-2883-000-0M', 'Molding', 'Produccion ', 'Celda 7', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-3467-000-0M', 'Molding', 'Produccion ', 'Celda 7', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('TRW-5875-000-0D', 'Molding', 'Produccion ', 'Celda 7', 'TRW');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-5671-000-0A', 'Molding', 'Produccion ', 'Celda 5', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-7900-000-00', 'Molding', 'Produccion ', 'Celda 5', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-7614-000', 'Molding', 'Produccion ', 'Celda 7', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-6194-100-00', 'Molding', 'Produccion ', 'Celda 6', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-6194-101-00', 'Molding', 'Produccion ', 'Celda 6', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-7567-100', 'Molding', 'NPI', 'Celda 4', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('SOG-8423-100', 'Molding', 'Produccion ', 'Celda 6', 'SOG');
INSERT INTO part(number, area, department, location, client) VALUES ('SOG-8423-101', 'Molding', 'Produccion ', 'Celda 6', 'SOG');
INSERT INTO part(number, area, department, location, client) VALUES ('VAL-6652-100', 'Molding', 'Produccion ', 'Celda 6', 'VAL');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-5670-000-00', 'Molding', 'Produccion ', 'Celda 5', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-5671-000-10-0B', 'Molding', 'Produccion ', 'Celda 5', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-6151-010-00', 'Molding', 'NPI', 'Celda 6', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-7567-001', 'Molding', 'Produccion ', 'Celda 4', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-6151-000-AB', 'Molding', 'Produccion ', 'Celda 5', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('VER-10011-101', 'Molding', 'Produccion ', 'Celda 7', 'VER');
INSERT INTO part(number, area, department, location, client) VALUES ('DAN-10000-001', 'Molding', 'Produccion ', 'Celda 7', 'DAN');
INSERT INTO part(number, area, department, location, client) VALUES ('DAN-9999-001', 'Molding', 'Produccion ', 'Celda 7', 'DAN');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-9224-100-01', 'Molding', 'NPI', 'Celda 4', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-6798-000-01', 'Molding', 'Produccion ', 'Celda 7', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-6798-080-01', 'Molding', 'Produccion ', 'Celda 7', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('VAL-8422-000-01', 'Molding', 'Produccion ', 'Celda 7', 'VAL');
INSERT INTO part(number, area, department, location, client) VALUES ('BRO-9112-000-01', 'Molding', 'NPI', 'Celda 3', 'BRO');
INSERT INTO part(number, area, department, location, client) VALUES ('BRO-9112-024-01', 'Molding', 'NPI', 'Celda 3', 'BRO');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-6428-100-00', 'Molding', 'Produccion ', 'Celda 7', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-6428-101-00', 'Molding', 'Produccion ', 'Celda 7', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-6428-102-00', 'Molding', 'Produccion ', 'Celda 7', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-6151-000-0A', 'Molding', 'Produccion ', 'Celda 5', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('TEK-8788-000-0A', 'Molding', 'Produccion ', 'Celda 3', 'TEK');
INSERT INTO part(number, area, department, location, client) VALUES ('BRO-9112-225-00', 'Molding', 'NPI', 'Celda 3', 'BRO');
INSERT INTO part(number, area, department, location, client) VALUES ('BRO-9112-990-00', 'Molding', 'NPI', 'Celda 3', 'BRO');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-3467-000-0N', 'Molding', 'Produccion ', 'Celda 7', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('SEM-3467-000-AN', 'Molding', 'Produccion ', 'Celda 7', 'SEM');
INSERT INTO part(number, area, department, location, client) VALUES ('VER-10012-100', 'Molding', 'Produccion ', 'Celda 7', 'VER');
INSERT INTO part(number, area, department, location, client) VALUES ('BOS-6194-010', 'Molding', 'NPI', 'Celda 6', 'BOS');
INSERT INTO part(number, area, department, location, client) VALUES ('EES-3647-000-0A', 'Molding', 'Produccion ', 'Celda 7', 'EES');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-6798-050', 'Molding', 'Produccion ', 'Celda 7', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('SEN-9810-000', 'Molding', 'NPI', 'Celda 4', 'SEN');
INSERT INTO part(number, area, department, location, client) VALUES ('BRO-9112-101-00', 'Molding', 'NPI', 'Celda 4', 'BRO');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-6725-050', 'Molding', 'Produccion ', 'Celda 7', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('SOG-8423-000-0B', 'Molding', 'Produccion ', 'Celda 7', 'SOG');
INSERT INTO part(number, area, department, location, client) VALUES ('AUT-9318-000', 'Cold Forging', 'Produccion ', 'Celda 2', 'AUT');
INSERT INTO part(number, area, department, location, client) VALUES ('AUT-9318-200', 'Cold Forging', 'Produccion ', 'Celda 2', 'AUT');
INSERT INTO part(number, area, department, location, client) VALUES ('AUT-9318-400', 'Cold Forging', 'Produccion ', 'Celda 2', 'AUT');
INSERT INTO part(number, area, department, location, client) VALUES ('RIV-9744-000-0C', 'Molding', 'NPI', 'Celda 6', 'RIV');
INSERT INTO part(number, area, department, location, client) VALUES ('RIV-9744-100', 'STA', 'NPI', 'Celda 1', 'RIV');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-6428-103-00', 'Molding', 'Produccion ', 'Celda 7', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-6428-104-00', 'Molding', 'Produccion ', 'Celda 7', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('DEN-6428-105-00', 'Molding', 'Produccion ', 'Celda 7', 'DEN');
INSERT INTO part(number, area, department, location, client) VALUES ('BRO-10027-010-MX', 'Molding', 'NPI', 'Celda 5', 'BRO');
INSERT INTO part(number, area, department, location, client) VALUES ('BRO-9112-024-00', 'Molding', 'NPI', 'Celda 3', 'BRO');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-5999-100-0A', 'Molding', 'Produccion ', 'Celda 7', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('COT-9997-000-0A', 'Molding', 'Produccion ', 'Celda 6', 'COT');
INSERT INTO part(number, area, department, location, client) VALUES ('EFI-7326-000', 'STA', 'Produccion ', 'Celda 1', 'EFI');
INSERT INTO part(number, area, department, location, client) VALUES ('EFI-7683-000', 'STA', 'Produccion ', 'Celda 1', 'EFI');
INSERT INTO part(number, area, department, location, client) VALUES ('EFI-7683-200', 'STA', 'Produccion ', 'Celda 1', 'EFI');
INSERT INTO part(number, area, department, location, client) VALUES ('EFI-7711-000', 'STA', 'Produccion ', 'Celda 1', 'EFI');
INSERT INTO part(number, area, department, location, client) VALUES ('EFI-7711-200', 'STA', 'Produccion ', 'Celda 1', 'EFI');
INSERT INTO part(number, area, department, location, client) VALUES ('EFI-7854-000-0A', 'STA', 'Produccion ', 'Celda 1', 'EFI');
INSERT INTO part(number, area, department, location, client) VALUES ('EMC-7272-000-00', 'STA', 'Produccion ', 'Celda 1', 'EMC');
INSERT INTO part(number, area, department, location, client) VALUES ('EPQ-5496-000-0D', 'STA', 'Produccion ', 'Celda 1', 'EPQ');
INSERT INTO part(number, area, department, location, client) VALUES ('FTE-1356-000-0W', 'STA', 'Produccion ', 'Celda 1', 'FTE');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-7364-000-00', 'STA', 'Produccion ', 'Celda 1', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-7759 STAMP', 'STA', 'Produccion ', 'Celda 1', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('HEL-7760 STAMP', 'STA', 'Produccion ', 'Celda 1', 'HEL');
INSERT INTO part(number, area, department, location, client) VALUES ('NID-10007-100', 'STA', 'Produccion ', 'Celda 1', 'NID');
INSERT INTO part(number, area, department, location, client) VALUES ('NID-10007-101', 'STA', 'Produccion ', 'Celda 1', 'NID');
INSERT INTO part(number, area, department, location, client) VALUES ('VER-10011-000', 'Molding', 'Produccion ', 'Celda 7', 'VER');
INSERT INTO part(number, area, department, location, client) VALUES ('VER-10011-100', 'Molding', 'Produccion ', 'Celda 7', 'VER');
INSERT INTO part(number, area, department, location, client) VALUES ('RIV-9744-000-0D', 'Molding', 'NPI', 'Celda 4', 'RIV');
INSERT INTO part(number, area, department, location, client) VALUES ('080-000020', 'Molding', 'Produccion ', 'Celda 5', 'XXX');
INSERT INTO part(number, area, department, location, client) VALUES ('6412-01 SUB ASSY', 'Molding', 'Produccion ', 'Celda 5', 'XXX');
INSERT INTO part(number, area, department, location, client) VALUES ('6412-02 SUB ASSY', 'Molding', 'Produccion ', 'Celda 5', 'XXX');
INSERT INTO part(number, area, department, location, client) VALUES ('6412-03 SUB ASSY', 'Molding', 'Produccion ', 'Celda 5', 'XXX');
INSERT INTO part(number, area, department, location, client) VALUES ('6412-A05 SUB ASSY', 'Molding', 'Produccion ', 'Celda 5', 'XXX');
