INSERT INTO problem VALUES ('Equipment Adjustment');
INSERT INTO problem VALUES ('Bubbles ');
INSERT INTO problem VALUES ('Contamination ');
INSERT INTO problem VALUES ('Fallen parts');
INSERT INTO problem VALUES ('Damaged part');
INSERT INTO problem VALUES ('Damaged part');
INSERT INTO problem VALUES ('MisingPart/WrongAssy.');
INSERT INTO problem VALUES ('Deformed pins');
INSERT INTO problem VALUES ('Degradation ');
INSERT INTO problem VALUES ('Dim. out of spec.');
INSERT INTO problem VALUES ('Hi Pot Fault');
INSERT INTO problem VALUES ('Incomplete part');
INSERT INTO problem VALUES ('Marks on surface(chips)');
INSERT INTO problem VALUES ('Damaged raw material');
INSERT INTO problem VALUES ('Destructive tests');
INSERT INTO problem VALUES ('Purges/Set Up');
INSERT INTO problem VALUES ('Last shots / progression');
INSERT INTO problem VALUES ('Plastic flash');
INSERT INTO problem VALUES ('Oxide');
INSERT INTO problem VALUES ('Eng. Tests');
INSERT INTO problem VALUES ('Plastic Excess');
INSERT INTO problem VALUES ('Retention Samples');
INSERT INTO problem VALUES ('Metallic Burr');
