INSERT INTO users(username, email, name, position) VALUES ('a.ayala', 'a.ayala@mx.interplex.com', 'Adriana Ayala', 'user');
INSERT INTO users(username, email, name, position) VALUES ('a.briones', 'a.briones@mx.interplex.com', 'Armando Briones', 'user');
INSERT INTO users(username, email, name, position) VALUES ('a.cortes', 'a.cortes@mx.interplex.com', 'Alma Cortes', 'user');
INSERT INTO users(username, email, name, position) VALUES ('a.dealba', 'a.dealba@mx.interplex.com', 'Alejandra DeAlba', 'user');
INSERT INTO users(username, email, name, position) VALUES ('a.delacruz', 'a.delacruz@mx.interplex.com', 'Adriana De La Cruz', 'user');
INSERT INTO users(username, email, name, position) VALUES ('a.diaz', 'a.diaz@mx.interplex.com', 'Abigail Diaz', 'user');
INSERT INTO users(username, email, name, position) VALUES ('a.dominguez', 'a.dominguez@mx.interplex.com', 'Alicia Dominguez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('a.gonzalez', 'a.gonzalez@mx.interplex.com', 'Alan Gonzalez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('a.gudino', 'a.gudino@mx.interplex.com', 'Aracely Gudino', 'user');
INSERT INTO users(username, email, name, position) VALUES ('a.longoria', 'a.longoria@mx.interplex.com', 'Ariel Longoria', 'user');
INSERT INTO users(username, email, name, position) VALUES ('a.perez', 'a.perez@mx.interplex.com', 'Adrian Perez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('A.PINEDO', 'A.PINEDO@mx.interplex.com', 'Arcenia PINEDO', 'user');
INSERT INTO users(username, email, name, position) VALUES ('a.prieto', 'a.prieto@mx.interplex.com', 'Arlette Prieto', 'user');
INSERT INTO users(username, email, name, position) VALUES ('a.salcedo', 'a.salcedo@mx.interplex.com', 'Aldo Salcedo', 'user');
INSERT INTO users(username, email, name, position) VALUES ('a.vega', 'a.vega@mx.interplex.com', 'Alfredo Vega', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Abiu.Esparza', 'Abiu.Esparza@mx.interplex.com', 'Abiu Esparza', 'user');
INSERT INTO users(username, email, name, position) VALUES ('ad.gonzalez', 'ad.gonzalez@mx.interplex.com', 'Adelayda Gonzalez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('adela.flores', 'adela.flores@mx.interplex.com', 'Adela Flores', 'user');
INSERT INTO users(username, email, name, position) VALUES ('admin', 'gdlac11@mx.interplex.com', 'Administrador', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Adolfo.Castellanos', 'Adolfo.Castellanos@mx.interplex.com', 'Adolfo Castellanos', 'user');
INSERT INTO users(username, email, name, position) VALUES ('adolfo.ramirez', 'adolfo.ramirez@mx.interplex.com', 'Adolfo Ramirez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('agustin.cortes', 'agustin.cortes@mx.interplex.com', 'Agustin Cortes', 'user');
INSERT INTO users(username, email, name, position) VALUES ('al.diaz', 'al.diaz@mx.interplex.com', 'Alan Diaz', 'user');
INSERT INTO users(username, email, name, position) VALUES ('al.gonzalez', 'al.gonzalez@mx.interplex.com', 'Alejandra Gonzalez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('alberto.orozco', 'alberto.orozco@mx.interplex.com', 'Alberto Orozco', 'user');
INSERT INTO users(username, email, name, position) VALUES ('alberto.sa', 'alberto.sa@mx.interplex.com', 'Alberto Sanchez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Alberto.Ve', 'Alberto.Ve@mx.interplex.com', 'Alberto Velazquez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('alejandra.deal', 'alejandra.deal@mx.interplex.com', 'Alejandra De Alba', 'user');
INSERT INTO users(username, email, name, position) VALUES ('alfredo.am', 'alfredo.am@mx.interplex.com', 'Alfredo Amezquita', 'user');
INSERT INTO users(username, email, name, position) VALUES ('alfredo.en', 'alfredo.en@mx.interplex.com', 'Alfredo Enriquez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('alfredo.fo', 'alfredo.fo@mx.interplex.com', 'Alfredo Fonseca', 'user');
INSERT INTO users(username, email, name, position) VALUES ('alison.diaz', 'alison.diaz@mx.interplex.com', 'Alison Diaz', 'user');
INSERT INTO users(username, email, name, position) VALUES ('alleya.aguiar', 'alleya.aguiar@mx.interplex.com', 'Alleya Aguiar', 'user');
INSERT INTO users(username, email, name, position) VALUES ('alma.munoz', 'alma.munoz@mx.interplex.com', 'Alma Munoz', 'user');
INSERT INTO users(username, email, name, position) VALUES ('almacen', 'i.lopez@mx.interplex.com', 'Almacen', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Ana.Del', 'Ana.Del@mx.interplex.com', 'Ana Delgadillo', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Ana.Garcia', 'Ana.Garcia@mx.interplex.com', 'Ana Garcia', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Ana.Lemus', 'Ana.Lemus@mx.interplex.com', 'Ana Lemus', 'user');
INSERT INTO users(username, email, name, position) VALUES ('angel.avalos', 'angel.avalos@mx.interplex.com', 'Angel Avalos', 'user');
INSERT INTO users(username, email, name, position) VALUES ('angel.olivas', 'angel.olivas@mx.interplex.com', 'Angel Olivas', 'user');
INSERT INTO users(username, email, name, position) VALUES ('angeles.gra', 'angeles.gra@mx.interplex.com', 'Angeles Graniel', 'user');
INSERT INTO users(username, email, name, position) VALUES ('angeles.ri', 'angeles.ri@mx.interplex.com', 'Angeles Rivera', 'user');
INSERT INTO users(username, email, name, position) VALUES ('antonio.sanchez', 'antonio.sanchez@mx.interplex.com', 'Antonio Sanchez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('antonio.valdez', 'antonio.valdez@mx.interplex.com', 'Antonio Valdez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Araceli.Gudino', 'Araceli.Gudino@mx.interplex.com', 'Araceli Gudino', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Armando.Rincon', 'Armando.Rincon@mx.interplex.com', 'Armando Rincon Ortiz', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Arturo.ALVAREZ', 'Arturo.ALVAREZ@mx.interplex.com', 'Arturo ALVAREZ', 'user');
INSERT INTO users(username, email, name, position) VALUES ('arturo.gonzalez', 'i.lopez@mx.interplex.com', 'Arturo Gonzalez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('automatizacion', 'i.lopez@mx.interplex.com', 'Automatización', 'user');
INSERT INTO users(username, email, name, position) VALUES ('b.garcia', 'b.garcia@mx.interplex.com', 'Blanca Garcia', 'user');
INSERT INTO users(username, email, name, position) VALUES ('b.uribe', 'b.uribe@mx.interplex.com', 'Bertha URIBE', 'user');
INSERT INTO users(username, email, name, position) VALUES ('b.vazquez', 'b.vazquez@mx.interplex.com', 'Blanca Vazquez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('baltazar.mo', 'baltazar.mo@mx.interplex.com', 'Baltazar Mora', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Belen.Diaz', 'Belen.Diaz@mx.interplex.com', 'Belen Diaz', 'user');
INSERT INTO users(username, email, name, position) VALUES ('bernardo.mo', 'bernardo.mo@mx.interplex.com', 'Bernardo Monroy', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Blanca.Her', 'Blanca.Her@mx.interplex.com', 'Blanca Hernandez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('blas.castaneda', 'blas.castaneda@mx.interplex.com', 'Blas Castañeda', 'user');
INSERT INTO users(username, email, name, position) VALUES ('brenda.cruz', 'brenda.cruz@mx.interplex.com', 'Brenda Cruz', 'user');
INSERT INTO users(username, email, name, position) VALUES ('brenda.go', 'brenda.go@mx.interplex.com', 'Brenda Gonzalez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('brianda.flo', 'brianda.flo@mx.interplex.com', 'Brianda Flores', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Bryan.Segura', 'Bryan.Segura@mx.interplex.com', 'Bryan Segura', 'user');
INSERT INTO users(username, email, name, position) VALUES ('c.castillo', 'c.castillo@mx.interplex.com', 'Claudia Castillo', 'user');
INSERT INTO users(username, email, name, position) VALUES ('c.cervantes', 'c.cervantes@mx.interplex.com', 'Christian Cervantes', 'user');
INSERT INTO users(username, email, name, position) VALUES ('c.montes', 'c.montes@mx.interplex.com', 'Cesar Montes', 'user');
INSERT INTO users(username, email, name, position) VALUES ('c.nuno', 'c.nuno@mx.interplex.com', 'Carlos Nuno', 'user');
INSERT INTO users(username, email, name, position) VALUES ('c.ramirez', 'c.ramirez@mx.interplex.com', 'Cuahutemoc Ramirez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('c.toribio', 'c.toribio@mx.interplex.com', 'Carolina Toribio', 'user');
INSERT INTO users(username, email, name, position) VALUES ('c.velazquez', 'c.velazquez@mx.interplex.com', 'Carlos Velazquez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('calidad', 'i.lopez@mx.interplex.com', 'Calidad', 'user');
INSERT INTO users(username, email, name, position) VALUES ('calidad.tecnicos', 'i.lopez@mx.interplex.com', 'Tecnicos de Calidad', 'user');
INSERT INTO users(username, email, name, position) VALUES ('carlos.acosta', 'carlos.acosta@mx.interplex.com', 'Carlos Acosta', 'user');
INSERT INTO users(username, email, name, position) VALUES ('carlos.ca', 'carlos.ca@mx.interplex.com', 'Carlos Carrillo', 'user');
INSERT INTO users(username, email, name, position) VALUES ('carlos.cazares', 'i.lopez@mx.interplex.com', 'Carlos Cázares', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Carlos.Diaz', 'Carlos.Diaz@mx.interplex.com', 'Carlos D?az', 'user');
INSERT INTO users(username, email, name, position) VALUES ('carlos.patino', 'carlos.patino@mx.interplex.com', 'Carlos Pati?o', 'user');
INSERT INTO users(username, email, name, position) VALUES ('carlos.rangel', 'carlos.rangel@mx.interplex.com', 'Carlos Rangel', 'user');
INSERT INTO users(username, email, name, position) VALUES ('carlos.sahagun', 'carlos.sahagun@mx.interplex.com', 'Carlos Sahagun', 'user');
INSERT INTO users(username, email, name, position) VALUES ('carlos.vega', 'carlos.vega@mx.interplex.com', 'Carlos Vega', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Carolina.Guz', 'Carolina.Guz@mx.interplex.com', 'Carolina Guzman', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Catalina.Velasco', 'Catalina.Velasco@mx.interplex.com', 'Catalina Velasco', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Cecilia.Cor', 'Cecilia.Cor@mx.interplex.com', 'Cecilia Cortes', 'user');
INSERT INTO users(username, email, name, position) VALUES ('cesar.ascen', 'cesar.ascen@mx.interplex.com', 'Cesar Ascencio', 'user');
INSERT INTO users(username, email, name, position) VALUES ('cesar.fuentes', 'cesar.fuentes@mx.interplex.com', 'Cesar Fuentes', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Christian.Ascencio', 'Christian.Ascencio@mx.interplex.com', 'Christian Ascencio', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Claudia.Aguiar', 'Claudia.Aguiar@mx.interplex.com', 'Claudia Aguiar', 'user');
INSERT INTO users(username, email, name, position) VALUES ('cnc', 'i.lopez@mx.interplex.com', 'CNC', 'user');
INSERT INTO users(username, email, name, position) VALUES ('cold.forging', 'i.lopez@mx.interplex.com', 'Cold Forging', 'user');
INSERT INTO users(username, email, name, position) VALUES ('cristina.valle', 'cristina.valle@mx.interplex.com', 'Cristina Valle', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Cynthia.Gu', 'Cynthia.Gu@mx.interplex.com', 'Cynthia Guzman', 'user');
INSERT INTO users(username, email, name, position) VALUES ('d.aguilar', 'd.aguilar@mx.interplex.com', 'Diana Aguilar', 'user');
INSERT INTO users(username, email, name, position) VALUES ('D.AVALOS', 'D.AVALOS@mx.interplex.com', 'Daniel AVALOS', 'user');
INSERT INTO users(username, email, name, position) VALUES ('d.boyas', 'd.boyas@mx.interplex.com', 'Dalia Boyas', 'user');
INSERT INTO users(username, email, name, position) VALUES ('d.encino', 'd.encino@mx.interplex.com', 'Diego Encino', 'user');
INSERT INTO users(username, email, name, position) VALUES ('d.gonzalez', 'd.gonzalez@mx.interplex.com', 'Daniela Gonzalez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('d.lopez', 'd.lopez@mx.interplex.com', 'David Lopez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('d.martinez', 'd.martinez@mx.interplex.com', 'David Martinez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('daniel.hernandez', 'i.lopez@mx.interplex.com', 'Daniel Hernandez G', 'user');
INSERT INTO users(username, email, name, position) VALUES ('daniel.yanez', 'daniel.yanez@mx.interplex.com', 'Daniel Ya?ez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('David.Cortes', 'David.Cortes@mx.interplex.com', 'David CORTES', 'user');
INSERT INTO users(username, email, name, position) VALUES ('david.moreno', 'david.moreno@mx.interplex.com', 'David Moreno', 'user');
INSERT INTO users(username, email, name, position) VALUES ('david.torres', 'david.torres@mx.interplex.com', 'David Torres', 'user');
INSERT INTO users(username, email, name, position) VALUES ('diana.delarosa', 'diana.delarosa@mx.interplex.com', 'Diana De la Rosa', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Diego.Molina', 'Diego.Molina@mx.interplex.com', 'Diego Molina', 'user');
INSERT INTO users(username, email, name, position) VALUES ('diego.rosa', 'diego.rosa@mx.interplex.com', 'Diego Rosa', 'user');
INSERT INTO users(username, email, name, position) VALUES ('dionicio.ji', 'dionicio.ji@mx.interplex.com', 'Dionicio Jimenez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('e.anaya', 'e.anaya@mx.interplex.com', 'Emmanuel Anaya', 'user');
INSERT INTO users(username, email, name, position) VALUES ('e.delgado', 'e.delgado@mx.interplex.com', 'Esteban Delgado', 'user');
INSERT INTO users(username, email, name, position) VALUES ('e.gamboa', 'e.gamboa@mx.interplex.com', 'Evelyn Gamboa', 'user');
INSERT INTO users(username, email, name, position) VALUES ('e.gonzalez', 'e.gonzalez@interplex.local', 'Eduardo Gonzalez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('e.jaramillo', 'e.jaramillo@mx.interplex.com', 'Eduwiges Jaramillo', 'user');
INSERT INTO users(username, email, name, position) VALUES ('e.leon', 'e.leon@mx.interplex.com', 'Eduardo Leon', 'user');
INSERT INTO users(username, email, name, position) VALUES ('e.martinez', 'e.martinez@mx.interplex.com', 'Esmeralda Martinez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('E.URIBE', 'E.URIBE@mx.interplex.com', 'Erick Uribe', 'user');
INSERT INTO users(username, email, name, position) VALUES ('e.vera', 'e.vera@mx.interplex.com', 'Eduardo Vera', 'user');
INSERT INTO users(username, email, name, position) VALUES ('edgar.o', 'edgar.o@mx.interplex.com', 'Edgar Ortega NPI', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Edgar.Ortega', 'Edgar.Ortega@mx.interplex.com', 'Edgar Ortega', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Eduardo.Marquez', 'Eduardo.Marquez@mx.interplex.com', 'Eduardo Marquez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('elizabeth.na', 'elizabeth.na@mx.interplex.com', 'Elizabeth Nava', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Elodia.Ca', 'Elodia.Ca@mx.interplex.com', 'Elodia Carrillo', 'user');
INSERT INTO users(username, email, name, position) VALUES ('embarques.almacen', 'i.lopez@mx.interplex.com', 'Almacen de Embarques', 'user');
INSERT INTO users(username, email, name, position) VALUES ('enrique.mo', 'enrique.mo@mx.interplex.com', 'Enrique Mondragon', 'user');
INSERT INTO users(username, email, name, position) VALUES ('ensamble', 'i.lopez@mx.interplex.com', 'Ensambles', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Erendirade.AVILA', 'Erendirade.AVILA@mx.interplex.com', 'Erendira de AVILA', 'user');
INSERT INTO users(username, email, name, position) VALUES ('erick.ro', 'erick.ro@mx.interplex.com', 'Erick Rodriguez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('erika.hernan', 'erika.hernan@mx.interplex.com', 'Erika Hernandez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Erika.Llanas', 'Erika.Llanas@mx.interplex.com', 'Erika Llanas', 'user');
INSERT INTO users(username, email, name, position) VALUES ('esmar.salgado', 'esmar.salgado@mx.interplex.com', 'Esmar Salgado', 'user');
INSERT INTO users(username, email, name, position) VALUES ('estampados', 'i.lopez@mx.interplex.com', 'Estampados', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Estefania.Mendez', 'Estefania.Mendez@mx.interplex.com', 'Estefania Mendez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('f.alferez', 'f.alferez@mx.interplex.com', 'Fernando Alferez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('f.lopez', 'f.lopez@mx.interplex.com', 'Felipe Lopez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('f.pablo', 'f.pablo@mx.interplex.com', 'Fernanda Pablo', 'user');
INSERT INTO users(username, email, name, position) VALUES ('f.tinoco', 'f.tinoco@mx.interplex.com', 'Fernando Tinoco', 'user');
INSERT INTO users(username, email, name, position) VALUES ('fabian.garcia', 'fabian.garcia@mx.interplex.com', 'Fabian Garcia', 'user');
INSERT INTO users(username, email, name, position) VALUES ('fabian.mejia', 'fabian.mejia@mx.interplex.com', 'Fabian Mejia', 'user');
INSERT INTO users(username, email, name, position) VALUES ('fabiola.alvarez', 'fabiola.alvarez@mx.interplex.com', 'Fabiola Alvarez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Fabiola.Garibay', 'Fabiola.Garibay@mx.interplex.com', 'Fabiola Garibay', 'user');
INSERT INTO users(username, email, name, position) VALUES ('fatima.ro', 'fatima.ro@mx.interplex.com', 'Fatima Rodriguez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('felicitas.ju', 'felicitas.ju@mx.interplex.com', 'Felicitas Juarez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('felipe.eze', 'felipe.eze@mx.interplex.com', 'Felipe Ezequiel', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Fernanda.FLORES', 'Fernanda.FLORES@mx.interplex.com', 'Fernanda FLORES', 'user');
INSERT INTO users(username, email, name, position) VALUES ('fernanda.ga', 'fernanda.ga@mx.interplex.com', 'Fernanda Garcia', 'user');
INSERT INTO users(username, email, name, position) VALUES ('fernando.go', 'fernando.go@mx.interplex.com', 'Fernando Gonzalez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('fernando.meraz', 'fernando.meraz@mx.interplex.com', 'Fernando Meraz', 'user');
INSERT INTO users(username, email, name, position) VALUES ('francisco.esparza', 'francisco.esparza@mx.interplex.com', 'Francisco Esparza', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Francisco.Martinez', 'Francisco.Martinez@mx.interplex.com', 'Francisco Martinez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Francisco.Rodriguez', 'Francisco.Rodriguez@mx.interplex.com', 'Francisco Rodríguez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('francisco.zu', 'francisco.zu@mx.interplex.com', 'Francisco Zuñiga', 'user');
INSERT INTO users(username, email, name, position) VALUES ('g.gutierrez', 'g.gutierrez@interplex.local', 'Guadalupe Gutierrez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('G.lizaola', 'G.lizaola@mx.interplex.com', 'Giovanni Lizaola', 'user');
INSERT INTO users(username, email, name, position) VALUES ('G.MAGDALENO', 'G.MAGDALENO@mx.interplex.com', 'Gerardo MAGDALENO', 'user');
INSERT INTO users(username, email, name, position) VALUES ('g.rubio', 'g.rubio@mx.interplex.com', 'Guadalupe Rubio', 'user');
INSERT INTO users(username, email, name, position) VALUES ('g.sarabia', 'g.sarabia@mx.interplex.com', 'Graciela Sarabia', 'user');
INSERT INTO users(username, email, name, position) VALUES ('g.verdejo', 'g.verdejo@mx.interplex.com', 'Gustavo Verdejo', 'user');
INSERT INTO users(username, email, name, position) VALUES ('gabriel.franco', 'gabriel.franco@mx.interplex.com', 'Gabriel Franco', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Gabriela.Li', 'Gabriela.Li@mx.interplex.com', 'Gabriela Lizaloa', 'user');
INSERT INTO users(username, email, name, position) VALUES ('gdl.ap', 'gdl.ap@mx.interplex.com', 'GDL Account Payable', 'user');
INSERT INTO users(username, email, name, position) VALUES ('gdl.comedor', 'gdl.comedor@mx.interplex.com', 'Gdl Comedor', 'user');
INSERT INTO users(username, email, name, position) VALUES ('gdl.nominaapp', 'gdl.nominaapp@mx.interplex.com', 'GDL NominaApp', 'user');
INSERT INTO users(username, email, name, position) VALUES ('gdl.nursing', 'gdl.nursing@mx.interplex.com', 'GDL Nursing', 'user');
INSERT INTO users(username, email, name, position) VALUES ('gdl.rh', 'gdl.rh@mx.interplex.com', 'IMexico GDL RH', 'user');
INSERT INTO users(username, email, name, position) VALUES ('gdlac11', 'gdlac11@mx.interplex.com', 'GDL Account Temp', 'user');
INSERT INTO users(username, email, name, position) VALUES ('gerardo.al', 'gerardo.al@mx.interplex.com', 'Gerardo Alvarin', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Gerardo.Alcantar', 'Gerardo.Alcantar@mx.interplex.com', 'Gerardo Alcantar', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Gerardo.Fuentes', 'Gerardo.Fuentes@mx.interplex.com', 'Gerardo FUENTES', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Gerardo.Rodriguez', 'Gerardo.Rodriguez@mx.interplex.com', 'Gerardo Rodriguez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('german.garcia', 'german.garcia@mx.interplex.com', 'German Garcia', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Gisela.Campos', 'Gisela.Campos@mx.interplex.com', 'Gisela Campos', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Gonzalo.Fernandez', 'Gonzalo.Fernandez@mx.interplex.com', 'Gonzalo Fernandez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Greg.Menn', 'Greg.Menn@mx.interplex.com', 'Greg Menn', 'user');
INSERT INTO users(username, email, name, position) VALUES ('griselda.flo', 'griselda.flo@mx.interplex.com', 'Griselda Flores', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Guadalupe.Benites', 'Guadalupe.Benites@mx.interplex.com', 'Guadalupe Benites', 'user');
INSERT INTO users(username, email, name, position) VALUES ('guadalupe.ja', 'guadalupe.ja@mx.interplex.com', 'Guadalupe Jaramillo', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Guillermina.rey', 'Guillermina.rey@mx.interplex.com', 'Guillermina Reynoso', 'user');
INSERT INTO users(username, email, name, position) VALUES ('guillermo.al', 'guillermo.al@mx.interplex.com', 'Guillermo Alcantar', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Guillermo.Alejandre', 'Guillermo.Alejandre@mx.interplex.com', 'Guillermo Alejandre Laija', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Guillermo.Alvarez', 'Guillermo.Alvarez@mx.interplex.com', 'Guillermo Alvarez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('hector.arnot', 'hector.arnot@mx.interplex.com', 'Hector Arnot', 'user');
INSERT INTO users(username, email, name, position) VALUES ('hector.ruiz', 'i.lopez@mx.interplex.com', 'Hector Ruiz', 'user');
INSERT INTO users(username, email, name, position) VALUES ('hector.za', 'hector.za@mx.interplex.com', 'Hector Zambrano', 'user');
INSERT INTO users(username, email, name, position) VALUES ('humberto.mo', 'humberto.mo@mx.interplex.com', 'Humberto Mondragon', 'user');
INSERT INTO users(username, email, name, position) VALUES ('i.arana', 'i.arana@mx.interplex.com', 'Ignacio Arana', 'user');
--INSERT INTO users(username, email, name, position) VALUES ('i.lopez', 'i.lopez@mx.interplex.com', 'Ivan Lopez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('i.merino', 'i.merino@mx.interplex.com', 'Israel Merino', 'user');
INSERT INTO users(username, email, name, position) VALUES ('i.pimentel', 'i.pimentel@mx.interplex.com', 'Isaac Pimentel', 'user');
INSERT INTO users(username, email, name, position) VALUES ('i.ruiz', 'i.ruiz@mx.interplex.com', 'Isela Ruiz', 'user');
INSERT INTO users(username, email, name, position) VALUES ('i.serrano', 'i.serrano@mx.interplex.com', 'Imelda Serrano', 'user');
INSERT INTO users(username, email, name, position) VALUES ('ibrahim.grayeb', 'ibrahim.grayeb@mx.interplex.com', 'Ibrahim Grayeb', 'user');
INSERT INTO users(username, email, name, position) VALUES ('imex.invoice', 'imex.invoice@mx.interplex.com', 'imex invoice', 'user');
INSERT INTO users(username, email, name, position) VALUES ('imex.security', 'imex.security@mx.interplex.com', 'IMEX Security', 'user');
INSERT INTO users(username, email, name, position) VALUES ('incoming', 'i.lopez@mx.interplex.com', 'Incoming', 'user');
INSERT INTO users(username, email, name, position) VALUES ('inspeccion', 'i.lopez@mx.interplex.com', 'Inspección', 'user');
INSERT INTO users(username, email, name, position) VALUES ('irving.calva', 'irving.calva@mx.interplex.com', 'Irving Calva', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Isabel.Ledezma', 'Isabel.Ledezma@mx.interplex.com', 'Isabel Ledezma', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Israel.Gonzalez', 'Israel.Gonzalez@mx.interplex.com', 'Israel Gonzalez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('israel.rodri', 'israel.rodri@mx.interplex.com', 'Israel Rodriguez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('ivan', 'diskman199@gmail.com', 'Ivan L', 'user');
INSERT INTO users(username, email, name, position) VALUES ('ivan.ramirez', 'ivan.ramirez@mx.interplex.com', 'Ivan Ramirez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('ivan.soto', 'ivan.soto@mx.interplex.com', 'Ivan Soto', 'user');
INSERT INTO users(username, email, name, position) VALUES ('ivanlopez', 'i.lopez@mx.interplex.com', 'Ivan Lopez Murillo', 'user');
INSERT INTO users(username, email, name, position) VALUES ('j.arechiga', 'j.arechiga@mx.interplex.com', 'Jesus Arechiga', 'user');
INSERT INTO users(username, email, name, position) VALUES ('j.chavez', 'j.chavez@mx.interplex.com', 'Jorge Chavez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('j.dedios', 'j.dedios@mx.interplex.com', 'Juan DeDios', 'user');
INSERT INTO users(username, email, name, position) VALUES ('j.garcia', 'j.garcia@mx.interplex.com', 'Jair Garcia', 'user');
INSERT INTO users(username, email, name, position) VALUES ('j.gomez', 'j.gomez@mx.interplex.com', 'Jesus Gomez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('j.gutierrez', 'j.gutierrez@mx.interplex.com', 'Jessica Gutierrez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('j.guzman', 'j.guzman@mx.interplex.com', 'Jorge Guzman', 'user');
INSERT INTO users(username, email, name, position) VALUES ('j.huerta', 'j.huerta@mx.interplex.com', 'Janet Huerta', 'user');
INSERT INTO users(username, email, name, position) VALUES ('j.lopez', 'j.lopez@mx.interplex.com', 'Juan Lopez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('j.moreno', 'j.moreno@mx.interplex.com', 'Juvenal Moreno', 'user');
INSERT INTO users(username, email, name, position) VALUES ('j.ramirez', 'j.ramirez@mx.interplex.com', 'Jose Ramirez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('j.romero', 'j.romero@mx.interplex.com', 'Jesus Romero', 'user');
INSERT INTO users(username, email, name, position) VALUES ('j.rosas', 'j.rosas@mx.interplex.com', 'Jorge Rosas', 'user');
INSERT INTO users(username, email, name, position) VALUES ('j.rubio', 'j.rubio@mx.interplex.com', 'Jesus Rubio', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Jacinto.Zuniga', 'Jacinto.Zuniga@mx.interplex.com', 'Jacinto Zu?iga Hernandez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('jadid.castro', 'jadid.castro@mx.interplex.com', 'Jadid Castro', 'user');
INSERT INTO users(username, email, name, position) VALUES ('jaime.ca', 'jaime.ca@mx.interplex.com', 'Jaime Carranza', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Jaime.Ramirez', 'Jaime.Ramirez@mx.interplex.com', 'Jaime Ramirez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('javier.valle', 'javier.valle@mx.interplex.com', 'Javier Del Valle', 'user');
INSERT INTO users(username, email, name, position) VALUES ('jesus.marquez', 'jesus.marquez@mx.interplex.com', 'Jesus Marquez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Jhovany.Vera', 'Jhovany.Vera@mx.interplex.com', 'Jhovany Vera', 'user');
INSERT INTO users(username, email, name, position) VALUES ('jocelyne.cuevas', 'jocelyne.cuevas@mx.interplex.com', 'Jocelyne Cuevas', 'user');
INSERT INTO users(username, email, name, position) VALUES ('jocelyne.na', 'jocelyne.na@mx.interplex.com', 'Jocelyne Navarro', 'user');
INSERT INTO users(username, email, name, position) VALUES ('jonathan.fo', 'jonathan.fo@mx.interplex.com', 'Jonathan Fonseca', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Jonathan.Valencia', 'Jonathan.Valencia@mx.interplex.com', 'Jonathan Valencia', 'user');
INSERT INTO users(username, email, name, position) VALUES ('jorge.albarran', 'jorge.albarran@mx.interplex.com', 'Jorge ALBARRAN', 'user');
INSERT INTO users(username, email, name, position) VALUES ('jorge.lopez', 'jorge.lopez@mx.interplex.com', 'Jorge Lopez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('jorge.sanchez', 'jorge.sanchez@mx.interplex.com', 'Jorge Sanchez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Jorge.Solorzano', 'Jorge.Solorzano@mx.interplex.com', 'Jorge Solorzano', 'user');
INSERT INTO users(username, email, name, position) VALUES ('jorge.torres', 'jorge.torres@mx.interplex.com', 'Jorge Torres', 'user');
INSERT INTO users(username, email, name, position) VALUES ('jose.cruz', 'i.lopez@mx.interplex.com', 'Jose Luis Cruz', 'user');
INSERT INTO users(username, email, name, position) VALUES ('jose.gonza', 'jose.gonza@mx.interplex.com', 'Jose Gonzalez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('jose.he', 'jose.he@mx.interplex.com', 'Jose Hernandez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Jose.Lopez', 'Jose.Lopez@mx.interplex.com', 'Jose Lopez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('jose.peralta', 'jose.peralta@mx.interplex.com', 'Jose Peralta', 'user');
INSERT INTO users(username, email, name, position) VALUES ('jose.vera', 'jose.vera@mx.interplex.com', 'Jose Vera', 'user');
INSERT INTO users(username, email, name, position) VALUES ('josue.diaz', 'josue.diaz@mx.interplex.com', 'Josue Diaz', 'user');
INSERT INTO users(username, email, name, position) VALUES ('juan.diaz', 'juan.diaz@mx.interplex.com', 'Juan Diaz', 'user');
INSERT INTO users(username, email, name, position) VALUES ('juan.go', 'juan.go@mx.interplex.com', 'Juan Gonzalez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('juan.rey', 'juan.rey@mx.interplex.com', 'Juan Rey', 'user');
INSERT INTO users(username, email, name, position) VALUES ('juan.zuniga', 'juan.zuniga@mx.interplex.com', 'Juan Zu?iga', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Julio.Perez', 'Julio.Perez@mx.interplex.com', 'Julio Perez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('k.ballesteros', 'k.ballesteros@mx.interplex.com', 'Kevin Ballesteros', 'user');
INSERT INTO users(username, email, name, position) VALUES ('k.dejesus', 'k.dejesus@mx.interplex.com', 'Karina dejesus', 'user');
INSERT INTO users(username, email, name, position) VALUES ('k.zuniga', 'k.zuniga@mx.interplex.com', 'Karina Zuniga', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Karen.Perez', 'Karen.Perez@mx.interplex.com', 'Karen Perez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Karina.go', 'Karina.go@mx.interplex.com', 'Karina Gonzalez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Karina.Gu', 'Karina.Gu@mx.interplex.com', 'Karina Gutierrez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Karla.Ramos', 'Karla.Ramos@mx.interplex.com', 'Karla Ramos', 'user');
INSERT INTO users(username, email, name, position) VALUES ('l.bautista', 'l.bautista@interplex.local', 'Lorena Bautista', 'user');
INSERT INTO users(username, email, name, position) VALUES ('l.bustamante', 'l.bustamante@mx.interplex.com', 'Lorena Bustamante', 'user');
INSERT INTO users(username, email, name, position) VALUES ('l.castro', 'l.castro@mx.interplex.com', 'Luis Castro', 'user');
INSERT INTO users(username, email, name, position) VALUES ('L.GALLARDO', 'L.GALLARDO@mx.interplex.com', 'Loreley GALLARDO', 'user');
INSERT INTO users(username, email, name, position) VALUES ('l.ramirez', 'l.ramirez@mx.interplex.com', 'Leonel Ramirez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('l.reyes', 'l.reyes@mx.interplex.com', 'Leonardo Reyes', 'user');
INSERT INTO users(username, email, name, position) VALUES ('l.ruiz', 'l.ruiz@mx.interplex.com', 'Luis Ruiz', 'user');
INSERT INTO users(username, email, name, position) VALUES ('laboratorio', 'i.lopez@mx.interplex.com', 'Laboratorio', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Laura.Mojarro', 'Laura.Mojarro@mx.interplex.com', 'Laura Mojarro', 'user');
INSERT INTO users(username, email, name, position) VALUES ('laura.munguia', 'laura.munguia@mx.interplex.com', 'Laura Munguia', 'user');
INSERT INTO users(username, email, name, position) VALUES ('leonardo.flo', 'leonardo.flo@mx.interplex.com', 'Leonardo Flores', 'user');
INSERT INTO users(username, email, name, position) VALUES ('leonel.ave', 'leonel.ave@mx.interplex.com', 'Leonel Avenda?o', 'user');
INSERT INTO users(username, email, name, position) VALUES ('leydi.lucas', 'leydi.lucas@mx.interplex.com', 'Leydi Lucas', 'user');
INSERT INTO users(username, email, name, position) VALUES ('linea', 'i.lopez@mx.interplex.com', 'Línea', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Lizette.Miranda', 'Lizette.Miranda@mx.interplex.com', 'Lizette Miranda', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Ludivina.Cruz', 'Ludivina.Cruz@mx.interplex.com', 'Ludivina Cruz', 'user');
INSERT INTO users(username, email, name, position) VALUES ('luis.aranda', 'luis.aranda@mx.interplex.com', 'Luis Aranda', 'user');
INSERT INTO users(username, email, name, position) VALUES ('luis.arzola', 'luis.arzola@mx.interplex.com', 'Luis Arzola', 'user');
INSERT INTO users(username, email, name, position) VALUES ('luis.blanco', 'luis.blanco@mx.interplex.com', 'Luis Blanco', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Luis.Cruz', 'Luis.Cruz@mx.interplex.com', 'Luis Cruz', 'user');
INSERT INTO users(username, email, name, position) VALUES ('luis.garcia', 'luis.garcia@mx.interplex.com', 'Luis Garcia', 'user');
INSERT INTO users(username, email, name, position) VALUES ('luis.rodriguez', 'luis.rodriguez@mx.interplex.com', 'Luis RODRIGUEZ', 'user');
INSERT INTO users(username, email, name, position) VALUES ('M.APOLINAR', 'M.APOLINAR@mx.interplex.com', 'Misael APOLINAR', 'user');
INSERT INTO users(username, email, name, position) VALUES ('m.briseno', 'm.briseno@mx.interplex.com', 'Manuel Briseno', 'user');
INSERT INTO users(username, email, name, position) VALUES ('m.castillo', 'm.castillo@mx.interplex.com', 'Miriam Castillo', 'user');
INSERT INTO users(username, email, name, position) VALUES ('m.oceguera', 'm.oceguera@mx.interplex.com', 'Martin Oceguera', 'user');
INSERT INTO users(username, email, name, position) VALUES ('M.RAMIREZ', 'M.RAMIREZ@mx.interplex.com', 'Monica RAMIREZ', 'user');
INSERT INTO users(username, email, name, position) VALUES ('m.santillan', 'm.santillan@mx.interplex.com', 'Mariana Santillan', 'user');
INSERT INTO users(username, email, name, position) VALUES ('m.silva', 'm.silva@mx.interplex.com', 'Manuel Silva', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Manuel.Gutierrez', 'Manuel.Gutierrez@mx.interplex.com', 'Manuel Gutierrez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Marcelo.Cortes', 'Marcelo.Cortes@mx.interplex.com', 'Marcelo Cortes', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Marco.Bueno', 'Marco.Bueno@mx.interplex.com', 'Marco Bueno', 'user');
INSERT INTO users(username, email, name, position) VALUES ('mario.danell', 'mario.danell@mx.interplex.com', 'Mario Danell', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Mario.Gonzalez', 'Mario.Gonzalez@mx.interplex.com', 'Mario Gonz?lez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Mario.Sanchez', 'Mario.Sanchez@mx.interplex.com', 'Mario Sanchez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Mario.Silva', 'Mario.Silva@mx.interplex.com', 'Mario Silva', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Marlene.Lau', 'Marlene.Lau@mx.interplex.com', 'Marlene Laureano', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Martha.MARTINEZ', 'Martha.MARTINEZ@mx.interplex.com', 'Martha MARTINEZ', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Martha.Rodriguez', 'Martha.Rodriguez@mx.interplex.com', 'Martha Rodriguez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('martin.olmedo', 'i.lopez@mx.interplex.com', 'Martin Olmedo', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Mauricio.Lopez', 'Mauricio.Lopez@mx.interplex.com', 'Mauricio Lopez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('mauricio.me', 'mauricio.me@mx.interplex.com', 'Mauricio Mendoza', 'user');
INSERT INTO users(username, email, name, position) VALUES ('metrologia.lab', 'i.lopez@mx.interplex.com', 'Laboratorio de Metrologia', 'user');
INSERT INTO users(username, email, name, position) VALUES ('miguel.juarez', 'miguel.juarez@mx.interplex.com', 'Miguel Juarez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('miguel.lopez', 'miguel.lopez@mx.interplex.com', 'Miguel Lopez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('moises.or', 'moises.or@mx.interplex.com', 'Moises Ornelas', 'user');
INSERT INTO users(username, email, name, position) VALUES ('moises.za', 'moises.za@mx.interplex.com', 'Moises Zarate', 'user');
INSERT INTO users(username, email, name, position) VALUES ('moldeo', 'i.lopez@mx.interplex.com', 'Moldeos', 'user');
INSERT INTO users(username, email, name, position) VALUES ('moncerrat.ma', 'moncerrat.ma@mx.interplex.com', 'Moncerrat Martinez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('N.LOPEZ', 'N.LOPEZ@mx.interplex.com', 'Nestor LOPEZ', 'user');
INSERT INTO users(username, email, name, position) VALUES ('n.trindade', 'n.trindade@mx.interplex.com', 'Nersis TRINDADE', 'user');
INSERT INTO users(username, email, name, position) VALUES ('nataly.jime', 'nataly.jime@mx.interplex.com', 'Nataly Jimenez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Nicolas.Frias', 'Nicolas.Frias@mx.interplex.com', 'Nicolas Frias', 'user');
INSERT INTO users(username, email, name, position) VALUES ('noemi.cortez', 'noemi.cortez@mx.interplex.com', 'Noemi Cortez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('norma.checa', 'norma.checa@mx.interplex.com', 'Norma Checa', 'user');
INSERT INTO users(username, email, name, position) VALUES ('o.camacho', 'o.camacho@mx.interplex.com', 'Oscar Camacho', 'user');
INSERT INTO users(username, email, name, position) VALUES ('o.hernandez', 'o.hernandez@mx.interplex.com', 'Omar Hernandez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('O.PEREZ', 'O.PEREZ@mx.interplex.com', 'Oscar PEREZ', 'user');
INSERT INTO users(username, email, name, position) VALUES ('olga.lopez', 'olga.lopez@mx.interplex.com', 'Olga Lopez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('omar.ortiz', 'omar.ortiz@mx.interplex.com', 'Omar Ortiz', 'user');
INSERT INTO users(username, email, name, position) VALUES ('operador', 'i.lopez@mx.interplex.com', 'operador', 'user');
INSERT INTO users(username, email, name, position) VALUES ('orlando.dean', 'orlando.dean@mx.interplex.com', 'Orlando De Anda', 'user');
INSERT INTO users(username, email, name, position) VALUES ('oscar.campos', 'oscar.campos@mx.interplex.com', 'Oscar Campos', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Oscar.Galindo', 'Oscar.Galindo@mx.interplex.com', 'Oscar Galindo', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Osvaldo.Del', 'Osvaldo.Del@mx.interplex.com', 'Osvaldo Delgado', 'user');
INSERT INTO users(username, email, name, position) VALUES ('osvaldo.ga', 'osvaldo.ga@mx.interplex.com', 'Osvaldo Garcia', 'user');
INSERT INTO users(username, email, name, position) VALUES ('osvaldo.lopez', 'osvaldo.lopez@mx.interplex.com', 'Osvaldo Lopez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('osvlo11', 'osvaldo.lopez@mx.interplex.com', 'osvlo11', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Oswaldo.Zazueta', 'Oswaldo.Zazueta@mx.interplex.com', 'Oswaldo Zazueta', 'user');
INSERT INTO users(username, email, name, position) VALUES ('p.alvarado', 'p.alvarado@mx.interplex.com', 'Paola Alvarado', 'user');
INSERT INTO users(username, email, name, position) VALUES ('P.CEJA', 'P.CEJA@mx.interplex.com', 'Pedro CEJA', 'user');
INSERT INTO users(username, email, name, position) VALUES ('p.chavoya', 'p.chavoya@mx.interplex.com', 'Pablo Chavoya', 'user');
INSERT INTO users(username, email, name, position) VALUES ('p.galvan', 'p.galvan@mx.interplex.com', 'Porfirio Galvan', 'user');
INSERT INTO users(username, email, name, position) VALUES ('p.martinez', 'p.martinez@mx.interplex.com', 'Paulina Martinez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('p.pacheco', 'p.pacheco@mx.interplex.com', 'Paola Pacheco', 'user');
INSERT INTO users(username, email, name, position) VALUES ('p.varela', 'p.varela@mx.interplex.com', 'Patricia Varela', 'user');
INSERT INTO users(username, email, name, position) VALUES ('pablo.alcala', 'pablo.alcala@mx.interplex.com', 'Pablo Alcala', 'user');
INSERT INTO users(username, email, name, position) VALUES ('pablo.juarez', 'pablo.juarez@mx.interplex.com', 'Pablo Juarez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('paola.chavez', 'paola.chavez@mx.interplex.com', 'Paola Chavez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('paola.murillo', 'paola.murillo@mx.interplex.com', 'Paola Murillo', 'user');
INSERT INTO users(username, email, name, position) VALUES ('patricia.rodriguez', 'patricia.rodriguez@mx.interplex.com', 'Patricia Rodriguez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Patricia.Romero', 'Patricia.Romero@mx.interplex.com', 'Patricia Romero', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Patricia.Toribio', 'Patricia.Toribio@mx.interplex.com', 'Patricia Toribio', 'user');
INSERT INTO users(username, email, name, position) VALUES ('paulina.mora', 'paulina.mora@mx.interplex.com', 'Paulina De La Mora', 'user');
INSERT INTO users(username, email, name, position) VALUES ('pedro.esparza', 'i.lopez@mx.interplex.com', 'Pedro Esparza', 'user');
INSERT INTO users(username, email, name, position) VALUES ('pedro.frutos', 'pedro.frutos@mx.interplex.com', 'Pedro Frutos', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Pinto.Cas', 'Pinto.Cas@mx.interplex.com', 'Pinto Castellanos', 'user');
INSERT INTO users(username, email, name, position) VALUES ('procesos', 'i.lopez@mx.interplex.com', 'Procesos', 'user');
INSERT INTO users(username, email, name, position) VALUES ('produccion', 'i.lopez@mx.interplex.com', 'Produccion', 'user');
INSERT INTO users(username, email, name, position) VALUES ('r.alcala', 'r.alcala@mx.interplex.com', 'Ricardo Alcala', 'user');
INSERT INTO users(username, email, name, position) VALUES ('r.cardenas', 'r.cardenas@mx.interplex.com', 'Roberto Cardenas', 'user');
INSERT INTO users(username, email, name, position) VALUES ('r.gomez', 'r.gomez@mx.interplex.com', 'Rodrigo Gomez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('r.iniguez', 'r.iniguez@mx.interplex.com', 'Ricardo Iniguez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('r.meza', 'r.meza@mx.interplex.com', 'Ricardo Meza', 'user');
INSERT INTO users(username, email, name, position) VALUES ('r.salcedo', 'r.salcedo@mx.interplex.com', 'Ricardo Salcedo', 'user');
INSERT INTO users(username, email, name, position) VALUES ('r.uzarraga', 'r.uzarraga@mx.interplex.com', 'Ruben Uzarraga', 'user');
INSERT INTO users(username, email, name, position) VALUES ('rafael.cruz', 'i.lopez@mx.interplex.com', 'Rafael de la Cruz', 'user');
INSERT INTO users(username, email, name, position) VALUES ('rafael.ro', 'rafael.ro@mx.interplex.com', 'Rafael Rodriguez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Ramiro.Zambrano', 'Ramiro.Zambrano@mx.interplex.com', 'Ramiro Zambrano', 'user');
INSERT INTO users(username, email, name, position) VALUES ('ramon.paredes', 'ramon.paredes@mx.interplex.com', 'Ramon Paredes', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Raul.Gonzalez', 'Raul.Gonzalez@mx.interplex.com', 'Raul Cadena Gonzalez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('refugio.va', 'refugio.va@mx.interplex.com', 'Refugio Vazquez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('rene.ro', 'rene.ro@mx.interplex.com', 'Rene Rodriguez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('ricard.collazo', 'i.lopez@mx.interplex.com', 'Ricardo Collazo', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Ricardo.Lopez', 'Ricardo.Lopez@mx.interplex.com', 'Ricardo L?pez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Ricardo.Ventura', 'Ricardo.Ventura@mx.interplex.com', 'Ricardo Ventura', 'user');
INSERT INTO users(username, email, name, position) VALUES ('rigoberto.ru', 'rigoberto.ru@mx.interplex.com', 'Rigoberto Rubio', 'user');
INSERT INTO users(username, email, name, position) VALUES ('roberto.ba', 'roberto.ba@mx.interplex.com', 'Roberto Barajas', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Rocio.Castro', 'Rocio.Castro@mx.interplex.com', 'Rocio Castro', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Rodrigo.Gamez', 'Rodrigo.Gamez@mx.interplex.com', 'Rodrigo Gamez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Rodrigo.Za', 'Rodrigo.Za@mx.interplex.com', 'Rodrigo Zambrano', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Rosaura.Lu', 'Rosaura.Lu@mx.interplex.com', 'Rosaura Lugo', 'user');
INSERT INTO users(username, email, name, position) VALUES ('ruben.go', 'ruben.go@mx.interplex.com', 'Ruben Gonzalez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('ruben.ortiz', 'ruben.ortiz@mx.interplex.com', 'Ruben Ortiz', 'user');
INSERT INTO users(username, email, name, position) VALUES ('ruben.quiroz', 'ruben.quiroz@mx.interplex.com', 'Ruben Quiroz', 'user');
INSERT INTO users(username, email, name, position) VALUES ('s.cortes', 's.cortes@mx.interplex.com', 'Susana Cortes', 'user');
INSERT INTO users(username, email, name, position) VALUES ('s.galvez', 's.galvez@mx.interplex.com', 'Santiago Galvez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('s.nieto', 's.nieto@mx.interplex.com', 'Socorro Nieto', 'user');
INSERT INTO users(username, email, name, position) VALUES ('s.olivares', 's.olivares@mx.interplex.com', 'Sandra Olivares', 'user');
INSERT INTO users(username, email, name, position) VALUES ('s.romero', 's.romero@mx.interplex.com', 'Sarahi Romero', 'user');
INSERT INTO users(username, email, name, position) VALUES ('salvador.cer', 'salvador.cer@mx.interplex.com', 'Salvador Cervantes', 'user');
INSERT INTO users(username, email, name, position) VALUES ('samantha.ri', 'samantha.ri@mx.interplex.com', 'Samantha Rivera', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Samuel.Ruiz', 'Samuel.Ruiz@mx.interplex.com', 'Samuel Ruiz', 'user');
INSERT INTO users(username, email, name, position) VALUES ('sandra.he', 'sandra.he@mx.interplex.com', 'Sandra Hernandez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Sandra.Ledezma', 'Sandra.Ledezma@mx.interplex.com', 'Sandra Ledezma', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Sandra.Quintero', 'Sandra.Quintero@mx.interplex.com', 'Sandra Quintero', 'user');
INSERT INTO users(username, email, name, position) VALUES ('santos.mata', 'santos.mata@mx.interplex.com', 'Santos Mata', 'user');
INSERT INTO users(username, email, name, position) VALUES ('sara.guzman', 'sara.guzman@mx.interplex.com', 'Sara Guzman', 'user');
INSERT INTO users(username, email, name, position) VALUES ('saul.velador', 'saul.velador@mx.interplex.com', 'Saul Velador', 'user');
INSERT INTO users(username, email, name, position) VALUES ('selma.gonzalez', 'selma.gonzalez@mx.interplex.com', 'Selma Gonzalez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('sergio.arre', 'sergio.arre@mx.interplex.com', 'Sergio Arredondo', 'user');
INSERT INTO users(username, email, name, position) VALUES ('sergio.go', 'sergio.go@mx.interplex.com', 'Sergio Gonzalez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('sergio.guerrero', 'sergio.guerrero@mx.interplex.com', 'Sergio Guerrero', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Set.Guzman', 'Set.Guzman@mx.interplex.com', 'Set Guzman', 'user');
INSERT INTO users(username, email, name, position) VALUES ('silverio.mu', 'silverio.mu@mx.interplex.com', 'Silverio Murillo', 'user');
INSERT INTO users(username, email, name, position) VALUES ('supervisores', 'i.lopez@mx.interplex.com', 'Supervisores', 'user');
INSERT INTO users(username, email, name, position) VALUES ('susana.castellanos', 'susana.castellanos@mx.interplex.com', 'Susana Castellanos', 'user');
INSERT INTO users(username, email, name, position) VALUES ('susana.ma', 'susana.ma@mx.interplex.com', 'Susana Martinez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Susana.Perez', 'Susana.Perez@mx.interplex.com', 'Susana Perez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('t.mora', 't.mora@interplex.local', 'Talia Mora', 'user');
INSERT INTO users(username, email, name, position) VALUES ('taller', 'i.lopez@mx.interplex.com', 'Taller', 'user');
INSERT INTO users(username, email, name, position) VALUES ('todos', 'i.lopez@mx.interplex.com', 'Todos', 'user');
INSERT INTO users(username, email, name, position) VALUES ('u.tovar', 'u.tovar@interplex.local', 'Ulises Tovar', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Ubaldo.Sanchez', 'Ubaldo.Sanchez@mx.interplex.com', 'Ubaldo Sanchez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('veronica.da', 'veronica.da@mx.interplex.com', 'Veronica Davalos', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Veronica.Rodriguez', 'Veronica.Rodriguez@mx.interplex.com', 'Veronica Rodriguez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Veronica.Villegas', 'Veronica.Villegas@mx.interplex.com', 'Veronica Villegas', 'user');
INSERT INTO users(username, email, name, position) VALUES ('vicente.vega', 'vicente.vega@mx.interplex.com', 'Vicente Vega', 'user');
INSERT INTO users(username, email, name, position) VALUES ('victor.criete', 'victor.criete@mx.interplex.com', 'Victor Criete', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Victor.Herrera', 'Victor.Herrera@mx.interplex.com', 'Victor Herrera', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Victor.Rivera', 'Victor.Rivera@mx.interplex.com', 'Victor Rivera', 'user');
INSERT INTO users(username, email, name, position) VALUES ('w.gonzalez', 'w.gonzalez@mx.interplex.com', 'Wendy Gonzalez', 'user');
INSERT INTO users(username, email, name, position) VALUES ('walter.deol', 'walter.deol@mx.interplex.com', 'Walter De Oliveira', 'user');
INSERT INTO users(username, email, name, position) VALUES ('y.cervantes', 'y.cervantes@mx.interplex.com', 'Yazmin Cervantes', 'user');
INSERT INTO users(username, email, name, position) VALUES ('Yanet.Lopez', 'Yanet.Lopez@mx.interplex.com', 'Yanet Lopez', 'user');
